#pragma once

// Auto-generated by CMake from Version.h.in — do not edit manually.
// Update the version in the root CMakeLists.txt project() command.

#define ENJIN_VERSION_MAJOR 0
#define ENJIN_VERSION_MINOR 9
#define ENJIN_VERSION_PATCH 5
#define ENJIN_VERSION_STRING "0.9.5"
