# Regenerates the embedded compute-shader registry that lets shipped Player
# builds create ComputePipelineHelper pipelines without loose .spv files:
#   Engine/include/Enjin/Renderer/EmbeddedComputeShaders.h   (light interface)
#   Engine/src/Renderer/EmbeddedComputeShaders.cpp           (byte arrays)
# Compile the shaders first (glslangValidator -V <shader> -o <shader>.spv),
# then: python _gen_compute.py
#
# Only shaders consumed through ComputePipelineHelper::Create belong here --
# systems that embed their own SPIR-V (ClusterComputeShaderData.h,
# SkinningComputeShaderData.h, RTShaderData.h) stay as they are.
import os

# Repo root, derived rather than hardcoded -- see _repo.py.
from _repo import ROOT as BASE
SHADERS = BASE + "/Engine/shaders"
HEADER = BASE + "/Engine/include/Enjin/Renderer/EmbeddedComputeShaders.h"
SOURCE = BASE + "/Engine/src/Renderer/EmbeddedComputeShaders.cpp"
NL = chr(10)

# (registry name = what ComputePipelineHelper::Create is called with, array name)
SHADER_LIST = [
    ("particle_simulate.comp", "ParticleSimulateSpv"),
    ("gpu_voxelize.comp",      "GpuVoxelizeSpv"),
    ("ddgi_probe_update.comp", "DdgiProbeUpdateSpv"),
    ("ddgi_sample.comp",       "DdgiSampleSpv"),
    ("volumetric_fog.comp",    "VolumetricFogSpv"),
]

def emit_array(name, data):
    lines = ["alignas(4) static const unsigned char %s[] = {" % name]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + " ".join("0x%02x," % b for b in chunk))
    lines.append("};")
    return NL.join(lines)

header = """#pragma once
// AUTO-GENERATED by _gen_compute.py -- do not edit by hand.
// Registry of embedded compute SPIR-V for shaders loaded through
// ComputePipelineHelper. In a dev tree the helper finds the loose .spv on
// disk; in a shipped Player there is no shader tree, so Create() falls back
// to this registry. Regenerate after editing any listed .comp source.

#include "Enjin/Platform/Platform.h"

namespace Enjin {
namespace Renderer {

struct EmbeddedComputeShader {
    const char* name;           // ComputePipelineHelper shader name, e.g. "particle_simulate.comp"
    const unsigned char* data;  // SPIR-V bytes
    unsigned size;
};

// Returns the registry entry for `name`, or nullptr if not embedded.
ENJIN_API const EmbeddedComputeShader* FindEmbeddedComputeShader(const char* name);

} // namespace Renderer
} // namespace Enjin
"""

arrays = []
entries = []
for fname, arr in SHADER_LIST:
    path = os.path.join(SHADERS, fname + ".spv")
    with open(path, "rb") as f:
        data = f.read()
    assert len(data) >= 20 and len(data) % 4 == 0 and data[:4] == b"\\x03\\x02\\x23\\x07".decode("unicode_escape").encode("latin1"), \
        "not SPIR-V: " + path
    arrays.append("// Engine/shaders/%s.spv (%d bytes)%s%s" % (fname, len(data), NL, emit_array(arr, data)))
    entries.append('    { "%s", %s, sizeof(%s) },' % (fname, arr, arr))

source = ("""// AUTO-GENERATED by _gen_compute.py -- do not edit by hand.
// Byte arrays live in this single TU (the lookup header is light) so the
// ~65KB of SPIR-V is not duplicated into every ComputePipelineHelper user.
// Guarded out of WebGPU builds: the only consumer (ComputePipelineHelper.h)
// is Vulkan-only, and Vulkan SPIR-V would be dead weight in the WASM.
#if !ENJIN_RENDERER_WEBGPU

#include "Enjin/Renderer/EmbeddedComputeShaders.h"
#include <cstring>

namespace Enjin {
namespace Renderer {

""" + (NL + NL).join(arrays) + """

static const EmbeddedComputeShader kRegistry[] = {
""" + NL.join(entries) + """
};

const EmbeddedComputeShader* FindEmbeddedComputeShader(const char* name) {
    if (!name) return nullptr;
    for (const EmbeddedComputeShader& e : kRegistry) {
        if (std::strcmp(e.name, name) == 0) return &e;
    }
    return nullptr;
}

} // namespace Renderer
} // namespace Enjin
#endif // !ENJIN_RENDERER_WEBGPU
""")

with open(HEADER, "w", newline=NL, encoding="ascii") as f:
    f.write(header)
with open(SOURCE, "w", newline=NL, encoding="ascii") as f:
    f.write(source)
print("wrote %s" % HEADER)
print("wrote %s (%d shaders)" % (SOURCE, len(SHADER_LIST)))
