# Regenerates Engine/src/Scripting/EnjinApiEmbedded.cpp from enjin_api/*.as.
# Run after editing any enjin_api script: python _gen_api.py
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
API_DIR = os.path.join(ROOT, 'enjin_api')
OUT = os.path.join(ROOT, 'Engine', 'src', 'Scripting', 'EnjinApiEmbedded.cpp')

files = sorted(f for f in os.listdir(API_DIR) if f.endswith('.as'))

out = []
out.append('// GENERATED by _gen_api.py from enjin_api/*.as - DO NOT EDIT BY HAND.')
out.append('//')
out.append('// The enjin_api script headers (TegeBehavior base class, Timer, Tween,')
out.append('// Math, StateMachine) are embedded in the engine so game scripts always')
out.append('// compile - no per-project copies required. On-disk enjin_api files, when')
out.append('// present, override these copies (modding / engine development).')
out.append('#include <cstring>')
out.append('')
out.append('namespace Enjin {')
out.append('namespace Scripting {')
out.append('')

for i, name in enumerate(files):
    src = open(os.path.join(API_DIR, name), encoding='utf-8').read()
    delim = 'ENJIN_API'
    while (')' + delim + '"') in src:
        delim += '_'
    out.append('static const char* s_Api%d = R"%s(' % (i, delim))
    out.append(src.rstrip('\n'))
    out.append(')%s";' % delim)
    out.append('')

out.append('const char* GetEmbeddedApiSource(const char* name) {')
for i, name in enumerate(files):
    out.append('    if (std::strcmp(name, "%s") == 0) return s_Api%d;' % (name, i))
out.append('    return nullptr;')
out.append('}')
out.append('')
out.append('// Back-compat name used by ScriptEngine for base-class injection')
out.append('const char* GetEmbeddedTegeBehaviorSource() {')
out.append('    return GetEmbeddedApiSource("TegeBehavior.as");')
out.append('}')
out.append('')
out.append('} // namespace Scripting')
out.append('} // namespace Enjin')

open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('wrote', OUT, '-', len(files), 'files embedded:', ', '.join(files))
