// The weather on a date is a pure function of the world seed and that date.
//
// It used to advance a running xorshift, so the sky on a given day depended on
// how many rolls had happened since the process booted. Load the same save
// twice and get different weather; two players on the same seed got different
// Tuesdays. A calendar game cannot promise a forecast on top of that.
//
// Two things here are worth not breaking:
//
//   1. The hash must AVALANCHE. Plain FNV-1a over sequential days leaves the
//      low bits correlated. The mean still comes out right, which is exactly
//      why it survives a glance -- but over 200 seeds the unfinished hash gave
//      between 0 and 35 snow days in a year that should hold 12, and 20 of the
//      200 produced a year with no snow at all.
//
//   2. It must stay byte-identical to the Shells year planner
//      (tools/shells_year.py), which previews the sky on days a designer left
//      blank. The pinned values below were generated from that tool. If these
//      fail, the preview and the game have drifted and one of them is lying.
#include "EnjinTest.h"
#include "Enjin/Effects/SeasonalWeather.h"
#include "Enjin/Effects/Weather.h"
#include "Enjin/Effects/WorldTime.h"

#include <string>

using namespace Enjin;
using namespace Enjin::Effects;

namespace {

// PickWeather reads exactly two things: the season, and the day of the year.
WorldTimeState OnDay(u32 dayOfYear) {
    WorldTimeState t;
    t.dayOfYear = dayOfYear;
    t.season = static_cast<Season>(((dayOfYear - 1) / 30) % 4);
    t.timeOfDay = 12.0f;
    t.normalizedTimeOfDay = 0.5f;
    t.daylightHours = 14.0f;
    return t;
}

SeasonalWeatherSystem SeededWith(const std::string& seed) {
    SeasonalWeatherSystem s;
    s.GetConfig().enabled = true;
    s.GetConfig().worldSeed = seed;
    return s;
}

u32 SnowDaysInAYear(const std::string& seed) {
    SeasonalWeatherSystem s = SeededWith(seed);
    u32 n = 0;
    for (u32 d = 1; d <= 120; ++d) {
        if (s.WeatherOn(OnDay(d)) == WeatherType::Snow) ++n;
    }
    return n;
}

} // namespace

ENJIN_TEST(DeterministicWeather, TheHashMatchesTheYearPlannerExactly) {
    // Generated by tools/shells_year.py in the Shells project. These are the
    // contract between the authoring tool and the runtime.
    struct Case { u32 day; u32 expected; };
    const Case shells1[] = {
        {  1, 3873689369u},
        {  2, 1338059703u},
        { 30, 2890761365u},
        { 31, 1065026245u},
        { 60, 1148712460u},
        { 91, 2646604508u},
        { 96, 2269260975u},
        {120, 2947901826u},
    };
    for (const Case& c : shells1) {
        ENJIN_EXPECT_TRUE(DateHash("shells-1", c.day) == c.expected);
    }

    // An empty seed is legal and must still be stable.
    ENJIN_EXPECT_TRUE(DateHash("", 1u) == 493982010u);
    ENJIN_EXPECT_TRUE(DateHash("", 42u) == 3977839916u);
    ENJIN_EXPECT_TRUE(DateHash("", 120u) == 3124126547u);
}

ENJIN_TEST(DeterministicWeather, TheSkyOnADateIsTheSameEveryTimeYouAsk) {
    // The old bug in one assertion: asking repeatedly used to advance the
    // stream, so the answer changed under you.
    SeasonalWeatherSystem s = SeededWith("shells-1");

    const WeatherType first = s.WeatherOn(OnDay(96));
    for (int i = 0; i < 500; ++i) {
        // Interleave other dates, which is what a forecast board would do.
        s.WeatherOn(OnDay(static_cast<u32>(1 + (i % 120))));
    }
    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(96)) == first);
}

ENJIN_TEST(DeterministicWeather, AFreshSystemAgreesWithAnOldOne) {
    // Reloading a save builds a new system. It must land on the same sky, which
    // is the whole promise: the weather you had is the weather you get back.
    SeasonalWeatherSystem played = SeededWith("tidepool-4821");
    for (u32 d = 1; d <= 60; ++d) played.WeatherOn(OnDay(d));   // a season of play

    SeasonalWeatherSystem reloaded = SeededWith("tidepool-4821");
    for (u32 d = 1; d <= 120; ++d) {
        ENJIN_EXPECT_TRUE(played.WeatherOn(OnDay(d)) == reloaded.WeatherOn(OnDay(d)));
    }
}

ENJIN_TEST(DeterministicWeather, ADifferentSeedIsADifferentYear) {
    SeasonalWeatherSystem a = SeededWith("shells-1");
    SeasonalWeatherSystem b = SeededWith("shells-2");

    u32 differences = 0;
    for (u32 d = 1; d <= 120; ++d) {
        if (a.WeatherOn(OnDay(d)) != b.WeatherOn(OnDay(d))) ++differences;
    }
    // Two unrelated years should not agree on most of their days.
    ENJIN_EXPECT_TRUE(differences > 40);
}

ENJIN_TEST(DeterministicWeather, CloudyIsReachable) {
    // Cloudy has been in WeatherType all along, and PickWeather used to fall it
    // through to Clear. Fall is 30% cloudy, so nearly a third of autumn was
    // being reported as clear sky.
    SeasonalWeatherSystem s = SeededWith("shells-1");
    bool sawCloudy = false;
    for (u32 d = 61; d <= 90 && !sawCloudy; ++d) {          // fall
        sawCloudy = s.WeatherOn(OnDay(d)) == WeatherType::Cloudy;
    }
    ENJIN_EXPECT_TRUE(sawCloudy);
}

ENJIN_TEST(DeterministicWeather, EverySeedGetsAWinter) {
    // This is the avalanche, stated as the thing a player would notice. Without
    // the finalizer, 20 seeds in 200 produced a year with no snow in it at all,
    // and a game whose snow weather is a whole tool would silently lose it for
    // one player in ten.
    u32 lowest = 999, highest = 0, winterless = 0;
    for (int i = 1; i <= 200; ++i) {
        const u32 n = SnowDaysInAYear("shells-" + std::to_string(i));
        if (n < lowest) lowest = n;
        if (n > highest) highest = n;
        if (n == 0) ++winterless;
    }

    ENJIN_EXPECT_TRUE(winterless == 0);
    // The table says 12 snow days a year. Hold the spread near it rather than
    // pinning an exact count, which would only be pinning this hash.
    ENJIN_EXPECT_TRUE(lowest >= 3);
    ENJIN_EXPECT_TRUE(highest <= 25);
}

ENJIN_TEST(DeterministicWeather, SnowKeepsToTheSeasonsThatHaveIt) {
    // Spring and summer are 0.00 snow in the shipped table. A correct roll can
    // never produce one, and a biased hash is exactly how it would.
    SeasonalWeatherSystem s = SeededWith("shells-1");
    bool snowedOutOfSeason = false;
    for (u32 d = 1; d <= 60; ++d) {                          // spring + summer
        if (s.WeatherOn(OnDay(d)) == WeatherType::Snow) snowedOutOfSeason = true;
    }
    ENJIN_EXPECT_TRUE(!snowedOutOfSeason);
}

ENJIN_TEST(DeterministicWeather, DayOfYearIsTheThingTheHashCountsOn) {
    // dayOfYear is new state and it is the sole date input to the roll, so if
    // it ever stops advancing the whole year quietly freezes on one sky.
    WorldTimeSystem clock;
    clock.GetCalendarConfig().monthsPerYear = 4;    // Shells: a month is a season
    clock.GetCalendarConfig().daysPerMonth = 30;

    clock.SetTime(12.0f, 1, 1, 1);
    ENJIN_EXPECT_TRUE(clock.GetState().dayOfYear == 1u);

    clock.SetTime(12.0f, 30, 1, 1);
    ENJIN_EXPECT_TRUE(clock.GetState().dayOfYear == 30u);

    // First day of summer, and of fall, and the last day of the year.
    clock.SetTime(12.0f, 1, 2, 1);
    ENJIN_EXPECT_TRUE(clock.GetState().dayOfYear == 31u);
    clock.SetTime(12.0f, 1, 3, 1);
    ENJIN_EXPECT_TRUE(clock.GetState().dayOfYear == 61u);
    clock.SetTime(12.0f, 30, 4, 1);
    ENJIN_EXPECT_TRUE(clock.GetState().dayOfYear == 120u);

    // And the season the weather table is chosen from tracks it.
    ENJIN_EXPECT_TRUE(clock.GetState().season == Season::Winter);
}

ENJIN_TEST(DeterministicWeather, AnAuthoredDayAlwaysHappens) {
    // The one rule: a day with weather written on it always happens, a day left
    // blank is rolled from the seed. Both halves are asserted here because the
    // interesting failure is an authored day quietly getting rolled anyway.
    SeasonalWeatherSystem s = SeededWith("shells-1");

    const WeatherType rolled = s.WeatherOn(OnDay(40));
    s.SetAuthoredWeather(40, WeatherType::Storm);

    ENJIN_EXPECT_TRUE(s.IsAuthored(40));
    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(40)) == WeatherType::Storm);
    ENJIN_EXPECT_TRUE(s.GetAuthoredDayCount() == 1);

    // and it is still authored no matter how many times it is asked
    for (int i = 0; i < 50; ++i) s.WeatherOn(OnDay(static_cast<u32>(1 + i)));
    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(40)) == WeatherType::Storm);

    // clearing hands the day back to the seed, and it lands where it did before
    s.ClearAuthoredWeather(40);
    ENJIN_EXPECT_TRUE(!s.IsAuthored(40));
    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(40)) == rolled);
}

ENJIN_TEST(DeterministicWeather, AuthoredDaysSurviveASeedChange) {
    // This is what makes "new seed each playthrough" safe. Change the seed and
    // the blank days move; the authored days and the holidays pinned to them do
    // not. If this ever fails, a designer's calendar is at the mercy of a reroll.
    SeasonalWeatherSystem s = SeededWith("shells-1");
    s.SetAuthoredWeather(96, WeatherType::Snow);     // The Long Night
    s.SetAuthoredWeather(109, WeatherType::Clear);   // Grandad's Birthday

    u32 movedBlanks = 0;
    WeatherType before[121];
    for (u32 d = 1; d <= 120; ++d) before[d] = s.WeatherOn(OnDay(d));

    s.GetConfig().worldSeed = "tidepool-4821";
    for (u32 d = 1; d <= 120; ++d) {
        if (s.WeatherOn(OnDay(d)) != before[d]) ++movedBlanks;
    }

    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(96)) == WeatherType::Snow);
    ENJIN_EXPECT_TRUE(s.WeatherOn(OnDay(109)) == WeatherType::Clear);
    // the reroll has to actually do something, or this test proves nothing
    ENJIN_EXPECT_TRUE(movedBlanks > 30);
}

ENJIN_TEST_MAIN()
