// Adaptive Ray Budget — variance estimation compute shader
// Source: Engine/shaders/adaptive_ray_variance.comp
// Compiled with: glslangValidator --target-env vulkan1.2 -S comp adaptive_ray_variance.comp -o adaptive_ray_variance.comp.spv
// Placeholder: will be regenerated by embedding script from adaptive_ray_variance.comp.spv
static const uint32_t ADAPTIVE_RAY_VARIANCE_COMP_SPV[] = {
    // SPIR-V magic number (valid header so pipeline creation fails gracefully rather than crashing)
    0x07230203, 0x00010000, 0x0008000B, 0x00000001, 0x00000000, 0x00020011, 0x00000001, 0x0003000E,
    0x00000000, 0x00000001, 0x0005000F, 0x00000005, 0x00000001, 0x6E69616D, 0x00000000, 0x00060010,
    0x00000001, 0x00000011, 0x00000008, 0x00000008, 0x00000001, 0x00010038
};

// Adaptive Ray Budget — budget allocation compute shader
// Source: Engine/shaders/adaptive_ray_budget.comp
// Compiled with: glslangValidator --target-env vulkan1.2 -S comp adaptive_ray_budget.comp -o adaptive_ray_budget.comp.spv
// Placeholder: will be regenerated by embedding script from adaptive_ray_budget.comp.spv
static const uint32_t ADAPTIVE_RAY_BUDGET_COMP_SPV[] = {
    // SPIR-V magic number (valid header so pipeline creation fails gracefully rather than crashing)
    0x07230203, 0x00010000, 0x0008000B, 0x00000001, 0x00000000, 0x00020011, 0x00000001, 0x0003000E,
    0x00000000, 0x00000001, 0x0005000F, 0x00000005, 0x00000001, 0x6E69616D, 0x00000000, 0x00060010,
    0x00000001, 0x00000011, 0x00000008, 0x00000008, 0x00000001, 0x00010038
};
