// GENERATED by _gen_api.py from enjin_api/*.as - DO NOT EDIT BY HAND.
//
// The enjin_api script headers (TegeBehavior base class, Timer, Tween,
// Math, StateMachine) are embedded in the engine so game scripts always
// compile - no per-project copies required. On-disk enjin_api files, when
// present, override these copies (modding / engine development).
#include <cstring>

namespace Enjin {
namespace Scripting {

static const char* s_Api0 = R"ENJIN_API(
// CineSuite.as — Virtual Cinematography Suite for TEGE (The Enjin Game Engine)
// DAW-structured virtual film crew: Grip, Camera/Lens, Electric, Staging, Director, Monitoring.
// Works seamlessly with TegeBehavior and TEGE ECS.

enum DirectorStyle {
    Kubrick = 0,     // One-point perspective, constant velocity dolly, deep focus, pristine framing
    Hitchcock,       // Triad shot patterns, Vertigo dolly zoom, subject proximity holds
    Polanski,        // Claustrophobic tracking, wide lens proximity, locked eye-level
    Welles,          // Extreme low angles, deep focus crane oners, dynamic shadow ratios
    Spielberg,       // Retargeted oners, soft entrance/exit ramps, emotional zoom reveals
    Lucas,           // Graphic tableaux, dual-vcam wipe transitions, geometric staging
    Ford,            // Static frame holds, absolute look direction, subject frame exit
    Kurosawa         // Telephoto compression, A/B/C multicam coverage, dynamic group blocking
}

enum RigType {
    Fixed = 0,
    TrackedDolly,
    CraneArm,
    Handheld,
    OperatorHead
}

// -------------------------------------------------------------------
// SecondOrderDynamics — Deterministic spring-damper dynamics (f, zeta, r)
// Used across all TEGE camera rigs for natural inertia without physics engines.
// -------------------------------------------------------------------
class SecondOrderDynamics {
    float f = 2.0f;       // Frequency (speed of response)
    float zeta = 1.0f;    // Damping ratio (1.0 = critically damped, <1 = overshoot)
    float r = 0.0f;       // Initial response (0 = smooth start, >0 = immediate, <0 = anticipate)

    private Vector3 _xp;
    private Vector3 _y;
    private Vector3 _yd;

    private float _k1, _k2, _k3;

    void SetParams(float frequency, float dampingRatio, float initialResponse, Vector3 x0) {
        f = frequency;
        zeta = dampingRatio;
        r = initialResponse;

        float pi = 3.14159265f;
        float w = 2.0f * pi * f;
        _k1 = zeta / (pi * f);
        _k2 = 1.0f / (w * w);
        _k3 = r * zeta / (2.0f * pi * f);

        _xp = x0;
        _y = x0;
        _yd = Vector3(0, 0, 0);
    }

    Vector3 Update(float dt, Vector3 x, Vector3 xd) {
        if (dt <= 0.0001f) return _y;

        // Recalculate coefficients for dynamic stability
        float pi = 3.14159265f;
        float w = 2.0f * pi * f;
        _k1 = zeta / (pi * f);
        _k2 = 1.0f / (w * w);
        _k3 = r * zeta / (2.0f * pi * f);

        _y = _y + _yd * dt;
        _yd = _yd + (x + xd * _k3 - _y - _yd * _k1) / _k2 * dt;
        return _y;
    }
}

// -------------------------------------------------------------------
// CineFocusPuller — Virtual Focus Puller Agent
// -------------------------------------------------------------------
class CineFocusPuller {
    float focusDistance = 5.0f;
    float apertureTStop = 2.8f;
    float skillLevel = 0.9f; // 0.0 - 1.0 (imperfection model)

    private float _targetDistance = 5.0f;
    private float _currentVel = 0.0f;

    void TrackSubject(Vector3 camPos, Vector3 subjectPos, float dt) {
        Vector3 diff = subjectPos - camPos;
        _targetDistance = sqrt(diff.x * diff.x + diff.y * diff.y + diff.z * diff.z);

        // Lag and smooth rack based on skill level
        float smoothness = (1.1f - skillLevel) * 0.25f + 0.05f;
        focusDistance = focusDistance + (_targetDistance - focusDistance) * (dt / (dt + smoothness));
    }
}

// -------------------------------------------------------------------
// CineGaffer — Electric & Lighting Ratios
// -------------------------------------------------------------------
class CineGaffer {
    float keyIntensity = 1.0f;
    float fillRatio = 0.25f; // Key:Fill = 4:1
    float rimRatio = 0.50f;  // Key:Rim = 2:1

    float GetFillIntensity() { return keyIntensity * fillRatio; }
    float GetRimIntensity() { return keyIntensity * rimRatio; }

    float CalculateStopDelta(float lightA, float lightB) {
        if (lightB <= 0.0001f) return 0.0f;
        return log(lightA / lightB) / log(2.0f); // Ev stop delta
    }
}

// -------------------------------------------------------------------
// CineDirector — Canned Move Orchestrator
// -------------------------------------------------------------------
class CineDirector {
    DirectorStyle currentStyle = DirectorStyle::Kubrick;
    bool activeMove = false;
    float moveTime = 0.0f;
    float moveDuration = 3.0f;

    private Vector3 _startPos;
    private Vector3 _endPos;
    private float _startFocal = 50.0f;
    private float _endFocal = 50.0f;

    void Configure(DirectorStyle style) {
        currentStyle = style;
    }

    void TriggerVertigoDolly(Vector3 fromPos, Vector3 toPos, float startFocalLength, float endFocalLength, float duration) {
        _startPos = fromPos;
        _endPos = toPos;
        _startFocal = startFocalLength;
        _endFocal = endFocalLength;
        moveDuration = duration;
        moveTime = 0.0f;
        activeMove = true;
    }

    void Update(float dt, Vector3 &out currentPos, float &out currentFocal) {
        if (!activeMove) return;

        moveTime += dt;
        float t = moveTime / moveDuration;
        if (t >= 1.0f) {
            t = 1.0f;
            activeMove = false;
        }

        // Linear interpolation for strict Kubrick / Vertigo moves (no unintended ease-in/out)
        currentPos = _startPos + (_endPos - _startPos) * t;
        currentFocal = _startFocal + (_endFocal - _startFocal) * t;
    }
}

// -------------------------------------------------------------------
// TegeCineSuite — Master TEGE Behavior Component
// Attach to any entity with a Camera & Lens component in TEGE
// -------------------------------------------------------------------
class TegeCineSuite : TegeBehavior {
    [Property] int directorPreset = 0;
    [Property] uint64 primarySubjectId = 0;
    [Property] float defaultFocalLength = 35.0f;
    [Property] float keyLightRatio = 4.0f;
    [Property] bool enableDiagnosticOverlay = true;

    CineDirector director;
    CineFocusPuller focusPuller;
    CineGaffer gaffer;
    SecondOrderDynamics rigDynamics;

    void OnCreate() {
        director.Configure(DirectorStyle(directorPreset));
        Vector3 initialPos = GetPosition();
        rigDynamics.SetParams(2.0f, 1.0f, 0.0f, initialPos);
    }

    void SetDirector(DirectorStyle style) {
        directorPreset = int(style);
        director.Configure(style);
    }

    void OnUpdate(float dt) {
        // Auto focus puller tracking
        if (primarySubjectId != 0) {
            Vector3 subjPos = Entity_GetPosition(primarySubjectId);
            focusPuller.TrackSubject(GetPosition(), subjPos, dt);
        }

        // Live move updates
        Vector3 movePos;
        float focalLength = defaultFocalLength;
        if (director.activeMove) {
            director.Update(dt, movePos, focalLength);
            Vector3 dampedPos = rigDynamics.Update(dt, movePos, Vector3(0,0,0));
            SetPosition(dampedPos);
        }
    }

    void TriggerVertigoMove(Vector3 endPos, float endFocalLength, float duration) {
        director.TriggerVertigoDolly(GetPosition(), endPos, defaultFocalLength, endFocalLength, duration);
    }
}
)ENJIN_API";

static const char* s_Api1 = R"ENJIN_API(
// Math utility functions for TegeBehavior scripts
// These wrap the engine's registered global math functions.

// Note: Vector2, Vector3, Vector4, Quaternion are registered as native types
// by the engine. The following are convenience functions.

// Linearly interpolate between two Vector3 values
Vector3 LerpVector3(const Vector3 &in a, const Vector3 &in b, float t) {
    return Vector3(
        Lerp(a.x, b.x, t),
        Lerp(a.y, b.y, t),
        Lerp(a.z, b.z, t)
    );
}

// Move a Vector3 toward a target, capped by maxDelta
Vector3 MoveTowardsVector3(const Vector3 &in current, const Vector3 &in target, float maxDelta) {
    Vector3 diff = target - current;
    float dist = diff.Length();
    if (dist <= maxDelta || dist < 0.0001f) {
        return target;
    }
    return current + diff * (maxDelta / dist);
}

// Distance between two points
float Distance(const Vector3 &in a, const Vector3 &in b) {
    return (b - a).Length();
}

// Direction from a to b (normalized)
Vector3 Direction(const Vector3 &in from, const Vector3 &in to) {
    return (to - from).Normalized();
}

// Convert degrees to radians
float Deg2Rad(float degrees) {
    return degrees * 3.14159265f / 180.0f;
}

// Convert radians to degrees
float Rad2Deg(float radians) {
    return radians * 180.0f / 3.14159265f;
}
)ENJIN_API";

static const char* s_Api2 =
R"ENJIN_API(
// PortraitRig.as - one bust, built from swappable layers, driven by an emotion NAME.
//
// SHARED. Nothing in here knows what game it is in. It takes a string like
// "worried" and shows the right stack of layer entities. That is the whole
// contract, and it is why one file serves a conversation, an interrogation or
// a negotiation in different projects without a line of difference.
//
// THE SCENE HOLDS THE PIECES, THE RIG PICKS THEM. Runtime texture swapping is
// not a thing in TEGE, so every layer piece exists as its own entity and the
// rig toggles visibility. Attach this to the portrait ROOT; name the children by
// convention:
//
//   base_head            brow_neutral  brow_raised  brow_furrowed
//   brow_worried         brow_skeptical
//   eye_open  eye_half   eye_happy  eye_wide  eye_left  eye_right
//   eye_down  eye_teary  eye_squeezed  eye_closed
//   mouth_neutral  mouth_smile  mouth_open-smile  mouth_big-open  mouth_frown
//   mouth_small-o  mouth_gritted  mouth_pout  mouth_wavy
//   mouth_mid                      (lip-sync only: the halfway mouth)
//   blush_light  blush_heavy
//   fx_sweat  fx_anger  fx_tears  fx_sparkle  fx_gloom  fx_excl  fx_quest
//
// MISSING PIECES ARE FINE. A layer with no entity is skipped and recorded in
// Missing(), so a rig runs on two drawings and tells you what is not painted
// yet. That is the point: the emotion table can be finished long before the
// art is.
//
// Per CharacterExpressionSpec.md: the 10 MVP emotions ship on everyone, the
// full 16 on major characters. Auto-blink and look-toward are in here too,
// because the spec is right that they sell "alive" harder than emotion 17 does.
#include "TegeBehavior.as"

// The 16 emotions, each as "brow|eye|mouth|blush|fx". "-" means that layer is
// off for this emotion. THIS TABLE IS THE ONLY PLACE THE COMBOS LIVE. A
// character with different art overrides emoteTable; it does not fork the rig.
const string PORTRAIT_EMOTES =
    "neutral=neutral|open|neutral|-|-;"
    "smile=neutral|happy|smile|-|-;"
    "laugh=raised|happy|big-open|-|-;"
    "sad=worried|down|frown|-|-;"
    "angry=furrowed|wide|gritted|-|anger;"
    "surprised=raised|wide|small-o|-|excl;"
    "blush=worried|right|wavy|heavy|sweat;"
    "worried=worried|half|wavy|-|-;"
    "smug=skeptical|half|smile|-|-;"
    "flustered=raised|squeezed|open-smile|heavy|sweat;"
    "crying=worried|teary|frown|-|tears;"
    "thoughtful=furrowed|left|neutral|-|quest;"
    "disgusted=furrowed|half|pout|-|-;"
    "sleepy=neutral|half|small-o|-|gloom;"
    "flirty=skeptical|half|smile|light|sparkle;"
    "determined=furrowed|open|neutral|-|-";

class PortraitRig : TegeBehavior {
    // Override to give one character a different set of combos. Same format as
    // PORTRAIT_EMOTES; anything not named here falls back to the shared table.
    [Property] string emoteTable = "";
    [Property] string startEmote = "neutral";

    // WHO THIS BUST IS. A driver does not need a handle on this script; it
    // sends "portrait_emote" with who + emote and every rig in the scene checks
    // whether the name is its own. That keeps a driver from having to reach
    // across entities to move a face.
    [Property] string speakerId = "";

    // TWO BUSTS IN ONE SCENE. Layers are found by NAME through Scene_FindEntity,
    // which is scene-global, so a second rig would grab the first rig's pieces.
    // Give each rig a prefix and name its children "L_brow_neutral",
    // "R_brow_neutral" and so on. A scene with one bust can leave it empty.
    [Property] string layerPrefix = "";

    // Eye life. blinkEvery 0 turns blinking off, for a screenshot or for a
    // character whose eyes are covered.
    [Property] float blinkEvery = 3.4f;
    [Property] float blinkHold  = 0.09f;

    // Lip-sync, 3-phase (closed / mid / open). The spec says three is enough
    // when the words are text anyway. Speak(true) while the line is arriving.
    [Property] float mouthRate = 11.0f;

    array<string> layerName;      // every piece this rig knows how to show
    array<uint64> layerEnt;       // 0 = not in the scene
    array<string> absent;         // the pieces the art has not caught up to

    string emote = "";
    array<string> want;           // the layer names the current emote asks for
    float blinkT = 0.0f;
    bool  blinking = false;
    bool  talking = false;
    float mouthT = 0.0f;
    bool  mouthOpen = false;

    // ======================================================================
    void OnStart() {
        // Every piece either table mentions, plus the always-on base and the
        // lip-sync mouth, is looked up once. Scene_FindEntity is not free and
        // an emote change has to cost nothing.
        Claim("base_head");
        Claim("mouth_mid");
        Claim("eye_closed");
        Learn(PORTRAIT_EMOTES);
        if (emoteTable != "") Learn(emoteTable);

        Show("base_head", true);
        Set(startEmote);

        Events_Listen("portrait_emote", EventCallback(this.OnEmoteEvent));
        Events_Listen("portrait_speak", EventCallback(this.OnSpeakEvent));
        Events_Listen("portrait_look",  EventCallback(this.OnLookEvent));
    }

    // A rig with no speakerId answers to everything, which is what a debug
    // scene with one bust in it wants.
    bool Mine(const string &in who) {
        return speakerId == "" || who == "" || who == speakerId;
    }

    void OnEmoteEvent(const string &in ev) {
        if (Mine(Events_CurrentString("who"))) Set(Events_CurrentString("emote"));
    }

    void OnSpeakEvent(const string &in ev) {
        if (Mine(Events_CurrentString("who"))) Speak(Events_CurrentInt("on") != 0);
    }

    void OnLookEvent(const string &in ev) {
        if (Mine(Events_CurrentString("who"))) LookAt(Events_CurrentInt("dir"));
    }

    // Register every layer piece a table mentions.
    void Learn(const string &in table) {
        array<string> rows = Split(table, ";");
        for (uint i = 0; i < rows.length(); i++) {
            int eq = rows[i].findFirst("=");
            if (eq < 0) continue;
            array<string> parts = Split(rows[i].substr(eq + 1), "|");
            for (uint p = 0; p < parts.length() && p < 5; p++) {
                if (parts[p] == "" || parts[p] == "-") continue;
                Claim(Prefix(p) + parts[p]);
            }
        }
    }

    // Private, not global. A shared file must never introduce a global that
    // shadows or collides with a host script's own member, and game scripts
    // commonly define their own Split. enjin_api/StrUtil.as has these as
    // globals for scripts that want them.
    array<string> Split(const string &in s, const string &in sep) {
        array<string> parts;
        if (sep.length() == 0) { parts.insertLast(s); return parts; }
        int start = 0;
        while (true) {
            int at = s.findFirst(sep, uint(start));
            if (at < 0) {
                parts.insertLast(s.substr(uint(start), s.length() - uint(start)));
                break;
            }
            parts.insertLast(s.substr(uint(start), uint(at - start)));
            start = at + int(sep.length());
        }
        return parts;
    }

    string Prefix(uint slot) {
        if (slot == 0) return "brow_";
        if (slot == 1) return "eye_";
        if (slot == 2) return "mouth_";
        if (slot == 3) return "blush_";
        return "fx_";
    }

    void Claim(const string &in name) {
        for (uint i = 0; i < layerName.length(); i++)
            if (layerName[i] == name) return;
        uint64 e = Scene_FindEntity(layerPrefix + name);
        layerName.insertLast(name);
        layerEnt.insertLast(e);
        if (e == 0) absent.insertLast(name);
        else Entity_SetVisible(e, false);
    }

    void Show(const string &in name, bool on) {
        for (uint i = 0; i < layerName.length(); i++) {
            if (layerName[i] != name) continue;
            if (layerEnt[i] != 0) Entity_SetVisible(layerEnt[i], on);
)ENJIN_API"
R"ENJIN_API(            return;
        }
    }

    // ======================================================================
    // THE CONTRACT. One call, one string.
    void Set(const string &in name) {
        if (name == emote) return;
        string row = Lookup(emoteTable, name);
        if (row == "") row = Lookup(PORTRAIT_EMOTES, name);
        if (row == "") return;             // unknown emote: hold the last one

        for (uint i = 0; i < want.length(); i++) Show(want[i], false);
        want.resize(0);

        array<string> parts = Split(row, "|");
        for (uint p = 0; p < parts.length() && p < 5; p++) {
            if (parts[p] == "" || parts[p] == "-") continue;
            string n = Prefix(p) + parts[p];
            want.insertLast(n);
            Show(n, true);
        }
        emote = name;
        blinking = false;
        blinkT = 0.0f;
    }

    string Lookup(const string &in table, const string &in name) {
        if (table == "") return "";
        array<string> rows = Split(table, ";");
        for (uint i = 0; i < rows.length(); i++) {
            int eq = rows[i].findFirst("=");
            if (eq < 0) continue;
            if (rows[i].substr(0, eq) == name) return rows[i].substr(eq + 1);
        }
        return "";
    }

    string Emote() { return emote; }

    // What the art still owes you. Empty means the rig is fully dressed.
    string Missing() {
        string s = "";
        for (uint i = 0; i < absent.length(); i++)
            s += (i > 0 ? ", " : "") + absent[i];
        return s;
    }

    int MissingCount() { return int(absent.length()); }

    // The whole vocabulary, for a debug scene that wants to cycle it.
    array<string> Emotes() {
        array<string> names;
        array<string> rows = Split(PORTRAIT_EMOTES, ";");
        for (uint i = 0; i < rows.length(); i++) {
            int eq = rows[i].findFirst("=");
            if (eq > 0) names.insertLast(rows[i].substr(0, eq));
        }
        return names;
    }

    // ======================================================================
    // The mouth moves while a line is arriving, and settles back onto the
    // emotion's own mouth when it stops.
    void Speak(bool on) {
        if (talking == on) return;
        talking = on;
        if (!on) {
            Show("mouth_mid", false);
            MouthOfEmote(true);
            mouthOpen = false;
        }
        mouthT = 0.0f;
    }

    void MouthOfEmote(bool on) {
        for (uint i = 0; i < want.length(); i++)
            if (want[i].substr(0, 6) == "mouth_") Show(want[i], on);
    }

    // Look toward whoever is talking: -1 left, 0 ahead, 1 right, 2 down. Only
    // moves eyes that are plainly open, because teary / squeezed / happy-closed
    // are all carrying the expression and must not be overwritten by a glance.
    void LookAt(int dir) {
        for (uint i = 0; i < want.length(); i++) {
            if (want[i].substr(0, 4) != "eye_") continue;
            if (want[i] != "eye_open" && want[i] != "eye_left"
                && want[i] != "eye_right" && want[i] != "eye_down") return;
            Show(want[i], false);
            string n = dir < 0 ? "eye_left" : (dir == 1 ? "eye_right"
                     : (dir == 2 ? "eye_down" : "eye_open"));
            want[i] = n;
            Show(n, true);
            return;
        }
    }

    // ======================================================================
    void OnUpdate(float dt) {
        if (blinkEvery > 0.0f) {
            blinkT += dt;
            if (!blinking && blinkT >= blinkEvery) {
                blinking = true;  blinkT = 0.0f;
                EyesTo(false);    Show("eye_closed", true);
            } else if (blinking && blinkT >= blinkHold) {
                blinking = false; blinkT = 0.0f;
                Show("eye_closed", false);
                EyesTo(true);
            }
        }
        if (talking && mouthRate > 0.0f) {
            mouthT += dt;
            if (mouthT >= 1.0f / mouthRate) {
                mouthT = 0.0f;
                mouthOpen = !mouthOpen;
                Show("mouth_mid", mouthOpen);
                MouthOfEmote(!mouthOpen);
            }
        }
    }

    void EyesTo(bool on) {
        for (uint i = 0; i < want.length(); i++)
            if (want[i].substr(0, 4) == "eye_") Show(want[i], on);
    }
}
)ENJIN_API"
;

static const char* s_Api3 = R"ENJIN_API(
// Reactions.as - THE TAG SEAM.
//
// An option in a script carries a TAG, which is just a string. When the option
// fires, the tag comes here, and here is the only place that knows what it
// means. Two things come back out:
//
//   Emote(tag)   what the speaker's face does      -> PortraitRig.Set()
//   Delta(tag)   what it moves, and by how much    -> the game's own scalar
//
// That is the whole seam, and it is what lets one runtime serve several games.
// A dating sim maps "sharpened" onto affection; an interrogation maps the same
// tag onto suspicion; a third game maps it onto nothing at all. No game edits
// this file: each ships a Reaction data asset (data/schemas/reaction.enjschema)
// and names it.
//
//   tags      "verbatim;softened;sharpened;cut"
//   emotes    "neutral;worried;angry;sad"
//   statName  "affection"
//   deltas    "0;-1;1;-1"
//
// Authored in the editor's Data Assets panel. No build script, no recompile.
//
// USE. Not a behavior - make one and load it:
//   Reactions r;
//   r.Load("reactions/vn_default");
//   rig.Set(r.Emote(tag));
//   standing += r.Delta(tag);

class Reactions {
    array<string> tag;
    array<string> emote;
    array<float>  delta;
    string stat = "";
    string source = "";

    // Returns false when the asset is missing, and the table is then empty:
    // every Emote() answers "neutral" and every Delta() answers 0, so a scene
    // with no reaction asset still plays. It just plays flat.
    bool Load(const string &in asset) {
        tag.resize(0); emote.resize(0); delta.resize(0);
        source = asset;
        if (!DataAsset_Load(asset)) return false;

        tag  = Split(DataAsset_GetString(asset, "tags"), ";");
        stat = DataAsset_GetString(asset, "statName");
        array<string> em = Split(DataAsset_GetString(asset, "emotes"), ";");
        array<string> dl = Split(DataAsset_GetString(asset, "deltas"), ";");
        for (uint i = 0; i < tag.length(); i++) {
            emote.insertLast(i < em.length() ? em[i] : "neutral");
            delta.insertLast(i < dl.length() ? Num(dl[i]) : 0.0f);
        }
        return tag.length() > 0;
    }

    // Private, not global. A shared file must never introduce a global that
    // shadows or collides with a host script's own member. enjin_api/StrUtil.as
    // has these as globals for scripts that want them.
    array<string> Split(const string &in s, const string &in sep) {
        array<string> parts;
        if (sep.length() == 0) { parts.insertLast(s); return parts; }
        int start = 0;
        while (true) {
            int at = s.findFirst(sep, uint(start));
            if (at < 0) {
                parts.insertLast(s.substr(uint(start), s.length() - uint(start)));
                break;
            }
            parts.insertLast(s.substr(uint(start), uint(at - start)));
            start = at + int(sep.length());
        }
        return parts;
    }

    int RxDigit(const string &in c) {
        string digits = "0123456789";
        for (uint i = 0; i < 10; i++) if (digits.substr(i, 1) == c) return int(i);
        return -1;
    }

    // One decimal point, everything after it fractional. Deltas in a reaction
    // table are small and hand-authored, so this is enough. parseFloat does
    // exist here, but this skips stray separators and cannot throw on a cell an
    // author left half-typed, which is the failure that actually happens.
    float ToFloat(const string &in s) {
        float v = 0.0f, scale = 0.0f;
        bool neg = false, any = false;
        for (uint i = 0; i < s.length(); i++) {
            string c = s.substr(i, 1);
            if (i == 0 && c == "-") { neg = true; continue; }
            if (c == "." && scale == 0.0f) { scale = 1.0f; continue; }
            int d = RxDigit(c);
            if (d < 0) continue;
            any = true;
            if (scale == 0.0f) { v = v * 10.0f + float(d); }
            else { scale = scale * 0.1f; v = v + float(d) * scale; }
        }
        if (!any) return 0.0f;
        return neg ? -v : v;
    }

    int Index(const string &in t) {
        for (uint i = 0; i < tag.length(); i++)
            if (tag[i] == t) return int(i);
        return -1;
    }

    string Emote(const string &in t) {
        int i = Index(t);
        return i < 0 ? "neutral" : emote[i];
    }

    float Delta(const string &in t) {
        int i = Index(t);
        return i < 0 ? 0.0f : delta[i];
    }

    string StatName() { return stat; }
    bool Known(const string &in t) { return Index(t) >= 0; }

    // A tag a script uses that the table has never heard of is the failure mode
    // that costs an afternoon, because nothing errors: the face just never
    // moves. Hand this every tag the script can fire and it names the gaps.
    string Unknown(const array<string> &in used) {
        string s = "";
        for (uint i = 0; i < used.length(); i++) {
            if (used[i] == "" || Known(used[i])) continue;
            if (s.findFirst(used[i]) >= 0) continue;
            s += (s == "" ? "" : ", ") + used[i];
        }
        return s;
    }

    float Num(const string &in s) {
        // parseFloat on a stray empty cell gives 0, which is the right answer
        // for a tag that moves nothing.
        return s == "" ? 0.0f : ToFloat(s);
    }
}
)ENJIN_API";

static const char* s_Api4 = R"ENJIN_API(
// StateMachine.as — Simple finite state machine for game logic
// Usage:
//   class EnemyAI : TegeBehavior {
//       StateMachine fsm;
//
//       void OnStart() {
//           fsm.AddState("idle");
//           fsm.AddState("chase");
//           fsm.AddState("attack");
//           fsm.SetState("idle");
//       }
//
//       void OnUpdate(float dt) {
//           fsm.Update(dt);
//
//           if (fsm.IsState("idle")) {
//               // idle logic
//               if (playerNearby) fsm.SetState("chase");
//           } else if (fsm.IsState("chase")) {
//               // chase logic
//               if (inRange) fsm.SetState("attack");
//           }
//       }
//   }

class StateMachine {
    private string currentState;
    private string previousState;
    private float stateTime;
    private array<string> states;

    StateMachine() {
        stateTime = 0.0f;
    }

    // Add a named state
    void AddState(const string &in name) {
        states.insertLast(name);
    }

    // Transition to a new state
    void SetState(const string &in name) {
        if (currentState == name) return;
        previousState = currentState;
        currentState = name;
        stateTime = 0.0f;
    }

    // Get the current state name
    string GetState() const {
        return currentState;
    }

    // Get the previous state name
    string GetPreviousState() const {
        return previousState;
    }

    // Check if currently in a specific state
    bool IsState(const string &in name) const {
        return currentState == name;
    }

    // Check if just entered this state (first frame)
    bool JustEntered(const string &in name) const {
        return currentState == name && stateTime == 0.0f;
    }

    // Get time spent in current state (seconds)
    float GetStateTime() const {
        return stateTime;
    }

    // Check if a state exists
    bool HasState(const string &in name) const {
        for (uint i = 0; i < states.length(); i++) {
            if (states[i] == name) return true;
        }
        return false;
    }

    // Get number of registered states
    uint GetStateCount() const {
        return states.length();
    }

    // Call each frame to track time in state
    void Update(float dt) {
        stateTime += dt;
    }

    // Reset to no state
    void Reset() {
        previousState = currentState;
        currentState = "";
        stateTime = 0.0f;
    }
}
)ENJIN_API";

static const char* s_Api5 = R"ENJIN_API(
// StrUtil.as - the string helpers every data-driven script ends up rewriting.
//
// WHY THIS EXISTS. TEGE calls RegisterStdString but not RegisterStdStringUtils,
// and string::split() lives in the utils half, so THERE IS NO SPLIT ANYWHERE in
// AngelScript here. Every script that reads a joined string has grown its own
// private one, commonly as a class method. These are the same helpers as
// globals, once, so shared code can use them.
//
// parseInt / parseUInt / parseFloat / formatInt / formatFloat DO exist - they are
// registered in RegisterStdString_Native, which RegisterStdString calls. ToInt and
// ToFloat below are kept anyway because they never throw and they skip stray
// separators, which is what reading hand-authored joined data actually needs.
//
// The joined-string convention they serve: records separated by "|", fields
// within a record by ";". It exists because the Player's .enjdata loader only
// understands string / float / int / bool and silently DROPS StringArray and
// FloatArray, so a list that must survive a build has to travel as a string.

// Split "a;b;c" into its parts. An empty input gives one empty part, which is
// what you want: a slot with no options is one blank option, not zero.
array<string> Split(const string &in s, const string &in sep) {
    array<string> parts;
    if (sep.length() == 0) { parts.insertLast(s); return parts; }
    int start = 0;
    while (true) {
        int at = s.findFirst(sep, uint(start));
        if (at < 0) {
            parts.insertLast(s.substr(uint(start), s.length() - uint(start)));
            break;
        }
        parts.insertLast(s.substr(uint(start), uint(at - start)));
        start = at + int(sep.length());
    }
    return parts;
}

int StrDigit(const string &in c) {
    string digits = "0123456789";
    for (uint i = 0; i < 10; i++) if (digits.substr(i, 1) == c) return int(i);
    return -1;
}

// Non-digits are skipped rather than rejected, so "72" and " 72 " and "72;" all
// read as 72. An empty or digitless string is 0.
int ToInt(const string &in s) {
    int v = 0; bool neg = false, any = false;
    for (uint i = 0; i < s.length(); i++) {
        string c = s.substr(i, 1);
        if (i == 0 && c == "-") { neg = true; continue; }
        int d = StrDigit(c);
        if (d < 0) continue;
        v = v * 10 + d; any = true;
    }
    if (!any) return 0;
    return neg ? -v : v;
}

// One decimal point, everything after it fractional. "-1.5" and "0" and "" all
// behave. Deltas in a reaction table are small and hand-authored, so this is
// enough and it cannot throw.
float ToFloat(const string &in s) {
    float v = 0.0f, scale = 0.0f;
    bool neg = false, any = false;
    for (uint i = 0; i < s.length(); i++) {
        string c = s.substr(i, 1);
        if (i == 0 && c == "-") { neg = true; continue; }
        if (c == "." && scale == 0.0f) { scale = 1.0f; continue; }
        int d = StrDigit(c);
        if (d < 0) continue;
        any = true;
        if (scale == 0.0f) {
            v = v * 10.0f + float(d);
        } else {
            scale = scale * 0.1f;
            v = v + float(d) * scale;
        }
    }
    if (!any) return 0.0f;
    return neg ? -v : v;
}

// Trim ASCII whitespace off both ends. Authored data picked up by hand in an
// inspector field collects trailing spaces and they break every == comparison.
string Trim(const string &in s) {
    uint a = 0, b = s.length();
    while (a < b) {
        string c = s.substr(a, 1);
        if (c != " " && c != "\t" && c != "\n" && c != "\r") break;
        a++;
    }
    while (b > a) {
        string c = s.substr(b - 1, 1);
        if (c != " " && c != "\t" && c != "\n" && c != "\r") break;
        b--;
    }
    return s.substr(a, b - a);
}

string Join(const array<string> &in parts, const string &in sep) {
    string s = "";
    for (uint i = 0; i < parts.length(); i++)
        s += (i > 0 ? sep : "") + parts[i];
    return s;
}
)ENJIN_API";

static const char* s_Api6 = R"ENJIN_API(
// TegeBehavior — base class for all game scripts
// Inherit from this class to attach behavior to entities.
//
// Example:
//   class PlayerController : TegeBehavior {
//       [Property] float moveSpeed = 5.0f;
//
//       void OnUpdate(float dt) {
//           Vector3 move = Vector3(0, 0, 0);
//           if (Input_GetKey(Key::W)) move.z -= 1;
//           if (Input_GetKey(Key::S)) move.z += 1;
//           move = move.Normalized() * moveSpeed;
//           SetPosition(GetPosition() + move * dt);
//       }
//   }

class TegeBehavior {
    // Entity this behavior is attached to (set by the engine)
    uint64 _entityId;

    // Whether this behavior is enabled
    bool enabled = true;

    // --- Transform shortcuts ---

    Vector3 GetPosition() {
        return Entity_GetPosition(_entityId);
    }

    void SetPosition(const Vector3 &in pos) {
        Entity_SetPosition(_entityId, pos);
    }

    Vector3 GetRotation() {
        return Entity_GetRotation(_entityId);
    }

    void SetRotation(const Vector3 &in rot) {
        Entity_SetRotation(_entityId, rot);
    }

    Vector3 GetScale() {
        return Entity_GetScale(_entityId);
    }

    void SetScale(const Vector3 &in s) {
        Entity_SetScale(_entityId, s);
    }

    string GetName() {
        return Entity_GetName(_entityId);
    }

    uint64 GetEntity() {
        return _entityId;
    }

    // --- Coroutines ---

    uint StartCoroutine(const string &in funcName) {
        return ::StartCoroutine(funcName);
    }

    void StopCoroutine(uint id) {
        ::StopCoroutine(id);
    }

    void StopAllCoroutines() {
        ::StopAllCoroutines();
    }

    // --- Lifecycle callbacks (override in subclasses) ---
    // void OnCreate()                { }
    // void OnStart()                 { }
    // void OnUpdate(float dt)        { }
    // void OnFixedUpdate(float dt)   { }
    // void OnLateUpdate(float dt)    { }
    // void OnDestroy()               { }
    // void OnEnable()                { }
    // void OnDisable()               { }
    // void OnCollisionEnter(uint64 other) { }
    // void OnCollisionStay(uint64 other)  { }
    // void OnCollisionExit(uint64 other)  { }
    // void OnTriggerEnter(uint64 other)   { }
    // void OnTriggerExit(uint64 other)    { }
    // void OnMouseEnter()                 { }  // cursor ray first hits this entity (needs a collider)
    // void OnMouseExit()                  { }  // cursor ray leaves this entity
    // void OnClick()                      { }  // left click while the cursor is on this entity
}
)ENJIN_API";

static const char* s_Api7 = R"ENJIN_API(
// Timer.as — Countdown and repeating timer utility
// Usage:
//   class Spawner : TegeBehavior {
//       Timer spawnTimer;
//
//       void OnStart() {
//           spawnTimer.Start(2.0f, true); // 2 seconds, repeating
//       }
//
//       void OnUpdate(float dt) {
//           spawnTimer.Update(dt);
//           if (spawnTimer.JustFinished()) {
//               SpawnEnemy();
//           }
//       }
//   }

class Timer {
    private float duration;
    private float elapsed;
    private bool running;
    private bool repeating;
    private bool finished;
    private bool justFinishedFlag;
    private int repeatCount;
    private int maxRepeats; // -1 = infinite

    Timer() {
        duration = 0.0f;
        elapsed = 0.0f;
        running = false;
        repeating = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
        maxRepeats = -1;
    }

    // Start a one-shot timer
    void Start(float dur) {
        duration = dur;
        elapsed = 0.0f;
        running = true;
        repeating = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
        maxRepeats = -1;
    }

    // Start a repeating timer
    void Start(float dur, bool repeat) {
        Start(dur);
        repeating = repeat;
    }

    // Start a repeating timer with max repeat count
    void Start(float dur, bool repeat, int maxReps) {
        Start(dur);
        repeating = repeat;
        maxRepeats = maxReps;
    }

    // Stop the timer
    void Stop() {
        running = false;
    }

    // Resume a stopped timer
    void Resume() {
        if (!finished) running = true;
    }

    // Reset and stop
    void Reset() {
        elapsed = 0.0f;
        running = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
    }

    // Reset and immediately restart
    void Restart() {
        elapsed = 0.0f;
        running = true;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
    }

    // Call every frame
    void Update(float dt) {
        justFinishedFlag = false;
        if (!running || finished) return;

        elapsed += dt;
        if (elapsed >= duration) {
            justFinishedFlag = true;
            repeatCount++;

            if (repeating) {
                if (maxRepeats >= 0 && repeatCount >= maxRepeats) {
                    finished = true;
                    running = false;
                } else {
                    // Carry over excess time for accurate repeating
                    elapsed -= duration;
                }
            } else {
                finished = true;
                running = false;
                elapsed = duration;
            }
        }
    }

    // True only on the frame the timer completes (or each repeat cycle)
    bool JustFinished() const {
        return justFinishedFlag;
    }

    // True if the timer has completed (and is not repeating, or max repeats reached)
    bool IsFinished() const {
        return finished;
    }

    // True if the timer is actively counting
    bool IsRunning() const {
        return running;
    }

    // Progress from 0 to 1
    float GetProgress() const {
        if (duration <= 0.0f) return 1.0f;
        return Clamp(elapsed / duration, 0.0f, 1.0f);
    }

    // Time remaining
    float GetRemaining() const {
        float r = duration - elapsed;
        if (r < 0.0f) return 0.0f;
        return r;
    }

    // Time elapsed in current cycle
    float GetElapsed() const {
        return elapsed;
    }

    // Total duration
    float GetDuration() const {
        return duration;
    }

    // Number of times the timer has completed
    int GetRepeatCount() const {
        return repeatCount;
    }
}
)ENJIN_API";

static const char* s_Api8 = R"ENJIN_API(
// Tween.as — Easing and interpolation utilities for TegeBehavior scripts
// Usage:
//   float t = Tween::EaseInOut(elapsed / duration);
//   SetPosition(LerpVector3(startPos, endPos, t));

// Easing functions — all take t in [0,1] and return [0,1]
namespace Tween {

// Linear (no easing)
float Linear(float t) {
    return t;
}

// Quadratic
float EaseInQuad(float t) {
    return t * t;
}
float EaseOutQuad(float t) {
    return t * (2.0f - t);
}
float EaseInOutQuad(float t) {
    if (t < 0.5f) return 2.0f * t * t;
    return -1.0f + (4.0f - 2.0f * t) * t;
}

// Cubic
float EaseInCubic(float t) {
    return t * t * t;
}
float EaseOutCubic(float t) {
    float u = t - 1.0f;
    return u * u * u + 1.0f;
}
float EaseInOutCubic(float t) {
    if (t < 0.5f) return 4.0f * t * t * t;
    float u = 2.0f * t - 2.0f;
    return 0.5f * u * u * u + 1.0f;
}

// Quartic
float EaseInQuart(float t) {
    return t * t * t * t;
}
float EaseOutQuart(float t) {
    float u = t - 1.0f;
    return 1.0f - u * u * u * u;
}
float EaseInOutQuart(float t) {
    if (t < 0.5f) return 8.0f * t * t * t * t;
    float u = t - 1.0f;
    return 1.0f - 8.0f * u * u * u * u;
}

// Sine
float EaseInSine(float t) {
    return 1.0f - Cos(t * 3.14159265f * 0.5f);
}
float EaseOutSine(float t) {
    return Sin(t * 3.14159265f * 0.5f);
}
float EaseInOutSine(float t) {
    return 0.5f * (1.0f - Cos(3.14159265f * t));
}

// Exponential
float EaseInExpo(float t) {
    if (t <= 0.0f) return 0.0f;
    return Pow(2.0f, 10.0f * (t - 1.0f));
}
float EaseOutExpo(float t) {
    if (t >= 1.0f) return 1.0f;
    return 1.0f - Pow(2.0f, -10.0f * t);
}
float EaseInOutExpo(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    if (t < 0.5f) return 0.5f * Pow(2.0f, 20.0f * t - 10.0f);
    return 1.0f - 0.5f * Pow(2.0f, -20.0f * t + 10.0f);
}

// Back (overshoot)
float EaseInBack(float t) {
    float s = 1.70158f;
    return t * t * ((s + 1.0f) * t - s);
}
float EaseOutBack(float t) {
    float s = 1.70158f;
    float u = t - 1.0f;
    return u * u * ((s + 1.0f) * u + s) + 1.0f;
}
float EaseInOutBack(float t) {
    float s = 1.70158f * 1.525f;
    if (t < 0.5f) {
        float u = 2.0f * t;
        return 0.5f * (u * u * ((s + 1.0f) * u - s));
    }
    float u = 2.0f * t - 2.0f;
    return 0.5f * (u * u * ((s + 1.0f) * u + s) + 2.0f);
}

// Elastic
float EaseInElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    return -Pow(2.0f, 10.0f * t - 10.0f) * Sin((t * 10.0f - 10.75f) * (2.0f * 3.14159265f / 3.0f));
}
float EaseOutElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    return Pow(2.0f, -10.0f * t) * Sin((t * 10.0f - 0.75f) * (2.0f * 3.14159265f / 3.0f)) + 1.0f;
}
float EaseInOutElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    float c = (2.0f * 3.14159265f) / 4.5f;
    if (t < 0.5f)
        return -0.5f * Pow(2.0f, 20.0f * t - 10.0f) * Sin((20.0f * t - 11.125f) * c);
    return 0.5f * Pow(2.0f, -20.0f * t + 10.0f) * Sin((20.0f * t - 11.125f) * c) + 1.0f;
}

// Bounce
float EaseOutBounce(float t) {
    if (t < 1.0f / 2.75f) {
        return 7.5625f * t * t;
    } else if (t < 2.0f / 2.75f) {
        float u = t - 1.5f / 2.75f;
        return 7.5625f * u * u + 0.75f;
    } else if (t < 2.5f / 2.75f) {
        float u = t - 2.25f / 2.75f;
        return 7.5625f * u * u + 0.9375f;
    } else {
        float u = t - 2.625f / 2.75f;
        return 7.5625f * u * u + 0.984375f;
    }
}
float EaseInBounce(float t) {
    return 1.0f - EaseOutBounce(1.0f - t);
}
float EaseInOutBounce(float t) {
    if (t < 0.5f) return 0.5f * EaseInBounce(2.0f * t);
    return 0.5f * EaseOutBounce(2.0f * t - 1.0f) + 0.5f;
}

// Convenience aliases
float EaseIn(float t)    { return EaseInCubic(t); }
float EaseOut(float t)   { return EaseOutCubic(t); }
float EaseInOut(float t) { return EaseInOutCubic(t); }

} // namespace Tween

// Interpolation helpers using easing
float TweenFloat(float from, float to, float t) {
    return from + (to - from) * t;
}

Vector3 TweenVector3(const Vector3 &in from, const Vector3 &in to, float t) {
    return LerpVector3(from, to, t);
}
)ENJIN_API";

static const char* s_Api9 =
R"ENJIN_API(
// VNScene.as - the generic visual-novel / dating-sim beat player.
//
// SHARED. Nothing in here is about any one game. It reads a Conversation data
// asset, walks its beats, moves the speaker's face, offers you an answer where
// the author put one, and moves that character's affinity by whatever the
// reaction table says the tag is worth.
//
// THE WHOLE POINT IS THAT IT KNOWS NOTHING. A choice carries a bare tag string.
// This script hands the tag to Reactions.as and does what it is told. Swap the
// reaction asset and "tease" means something else, with no code change.
//
//   SPACE / ENTER / CLICK   advance a beat, or finish the line early
//   1 / 2 / 3               answer, where the beat has a choice
//
// WHAT THE SCENE MUST CONTAIN (build_vn_template.py makes all of it):
//   VN                  this script
//   Nameplate           text, who is talking
//   Line                text, what they say (revealed a character at a time)
//   Prompt              text, the hint line under the box
//   Opt0 Opt1 Opt2      text, the answers
//   PortraitLeft/Right  a PortraitRig each, layerPrefix "L_" and "R_"
//   DimLeft/DimRight    a dark quad over the bust that is not talking
//   MeterFillLeft/Right a quad whose X scale is that character's affinity
//   MeterNameLeft/Right text
//   BeatCount           text
//
// A missing entity is skipped, never an error, so the scene can be cut down.
#include "TegeBehavior.as"
#include "Reactions.as"

// Affinity survives a scene load through the meta store, so a template scene is
// a real starting point for a game with more than one conversation in it.
const string VN_AFFINITY = "vn.affinity.";

class VNScene : TegeBehavior {
    [Property] string conversation = "";   // a Conversation data asset

    // Used only when `conversation` is empty or missing, so the scene still
    // plays something rather than sitting blank.
    [Property] string fallbackLine = "No conversation asset loaded.";

    [Property] float revealRate = 42.0f;   // characters per second
    [Property] float meterWidth = 2.6f;    // world width of a full affinity bar
    [Property] int   startAffinity = 40;
    [Property] int   maxAffinity   = 100;

    // Affinity is carried between scenes through the meta store, which is the
    // point of it. A DEMO wants the opposite: press play twice and the meters
    // should not have crept up from last time. The shipped template sets this
    // true; a real game leaves it false and the relationship accumulates.
    [Property] int   resetOnStart = 0;

    // Auto-play. Seconds per beat; 0 means you play it by hand. Above 0 it
    // walks itself taking autoPick at every choice, which is how the template
    // gets captured without a hand on the keyboard.
    [Property] float autoBeat = 0.0f;
    [Property] int   autoPick = 1;

    Reactions rx;

    // --- the conversation, parsed ----------------------------------------
    array<string> castIds, castNames;
    array<string> beatWho, beatEmote, beatLine;
    array<string> beatChoice;            // "" or a choice-group index
    array<string> choiceWho, choiceText, choiceTags, choiceReply, choiceNote;
    array<string> outcomeTags, outcomeLines;
    array<int>    affinity;
    array<int>    target;        // where each character EXPECTS to be left

    // --- entities ---------------------------------------------------------
    uint64 nameplate = 0, lineEnt = 0, prompt = 0, beatCount = 0, closingEnt = 0;
    array<uint64> optEnt;
    array<uint64> dimEnt, fillEnt, meterName, meterVal, markEnt;
    array<uint64> noteEnt, verdictEnt;

    // --- state ------------------------------------------------------------
    int  beat = 0;
    int  mode = 0;              // 0 revealing, 1 waiting, 2 choosing, 3 done
    float shown = 0.0f;
    int  lineLen = 0;
    int  asking = -1;           // choice group being offered
    string pendingReply = "";   // a chosen option's answering line
    float autoT = 0.0f;

    // ======================================================================
    void OnStart() {
        nameplate  = Scene_FindEntity("Nameplate");
        lineEnt    = Scene_FindEntity("Line");
        prompt     = Scene_FindEntity("Prompt");
        beatCount  = Scene_FindEntity("BeatCount");
        closingEnt = Scene_FindEntity("Closing");
        for (int i = 0; i < 3; i++) {
            optEnt.insertLast(Scene_FindEntity("Opt" + i));
            // The consequence line under each answer. A choice with stakes that
            // will not say what it costs is a guess, not a decision.
            noteEnt.insertLast(Scene_FindEntity("Note" + i));
        }
        for (int i = 0; i < 2; i++) verdictEnt.insertLast(Scene_FindEntity("Verdict" + i));

        dimEnt.insertLast(Scene_FindEntity("DimLeft"));
        dimEnt.insertLast(Scene_FindEntity("DimRight"));
        fillEnt.insertLast(Scene_FindEntity("MeterFillLeft"));
        fillEnt.insertLast(Scene_FindEntity("MeterFillRight"));
        meterName.insertLast(Scene_FindEntity("MeterNameLeft"));
        meterName.insertLast(Scene_FindEntity("MeterNameRight"));
        meterVal.insertLast(Scene_FindEntity("MeterValLeft"));
        meterVal.insertLast(Scene_FindEntity("MeterValRight"));
        markEnt.insertLast(Scene_FindEntity("MeterMarkLeft"));
        markEnt.insertLast(Scene_FindEntity("MeterMarkRight"));

        Load();
        rx.Load(DataAsset_GetString(conversation, "reactions"));

        string gaps = rx.Unknown(AllTags());
        if (gaps != "")
            Debug_Log("VNScene: reaction table has no entry for: " + gaps);

        for (uint i = 0; i < castIds.length(); i++) {
            // Carried across scenes, so a second conversation continues where
            // the first left off rather than restarting the relationship.
            affinity.insertLast(resetOnStart != 0 ? startAffinity
                                : Meta_GetInt(VN_AFFINITY + castIds[i], startAffinity));
            Set(meterName[i], i < castNames.length() ? castNames[i] : castIds[i]);
        }
        PlaceMarks();
        DrawMeters();
        Set(closingEnt, "");
        for (uint i = 0; i < verdictEnt.length(); i++) Set(verdictEnt[i], "");
        Beat();
    }

    void Load() {
        if (conversation != "" && DataAsset_Load(conversation)) {
            castIds     = Split(DataAsset_GetString(conversation, "castIds"), ";");
            castNames   = Split(DataAsset_GetString(conversation, "castNames"), ";");
            beatWho     = Split(DataAsset_GetString(conversation, "beatWho"), "|");
            beatEmote   = Split(DataAsset_GetString(conversation, "beatEmote"), "|");
            beatLine    = Split(DataAsset_GetString(conversation, "beatLine"), "|");
            beatChoice  = Split(DataAsset_GetString(conversation, "beatChoice"), "|");
            choiceWho   = Split(DataAsset_GetString(conversation, "choiceWho"), "|");
            choiceText  = Split(DataAsset_GetString(conversation, "choiceText"), "|");
            choiceTags  = Split(DataAsset_GetString(conversation, "choiceTags"), "|");
            choiceReply = Split(DataAsset_GetString(conversation, "choiceReply"), "|");
            choiceNote  = Split(DataAsset_GetString(conversation, "choiceNote"), "|");
            target      = Ints(DataAsset_GetString(conversation, "castTarget"));
            outcomeTags  = Split(DataAsset_GetString(conversation, "outcomeTags"), ";");
            outcomeLines = Split(DataAsset_GetString(conversation, "outcomeLines"), ";");
            if (beatLine.length() > 0 && beatLine[0] != "") return;
        }
        // Nothing loaded. Say so on the page rather than showing a blank box,
        // because an empty VN scene and a broken one look identical otherwise.
        Debug_Log("VNScene: no conversation '" + conversation + "'");
        castIds.insertLast("left");   castNames.insertLast("");
        beatWho.insertLast("left");   beatEmote.insertLast("worried");
        beatLine.insertLast(fallbackLine);
)ENJIN_API"
R"ENJIN_API(        beatChoice.insertLast("");
    }

    array<string> AllTags() {
        array<string> all;
        for (uint i = 0; i < choiceTags.length(); i++) {
            array<string> t = Split(choiceTags[i], ";");
            for (uint j = 0; j < t.length(); j++) all.insertLast(t[j]);
        }
        return all;
    }

    // ======================================================================
    // Start the current beat: face, nameplate, dimming, and the line at zero
    // characters revealed.
    void Beat() {
        if (beat >= int(beatLine.length())) { Finish(); return; }

        string who = beat < int(beatWho.length()) ? beatWho[beat] : "";
        string emo = beat < int(beatEmote.length()) ? beatEmote[beat] : "neutral";

        FireEmote(who, emo);
        Speak(who, true);
        Set(nameplate, NameOf(who));
        Set(beatCount, "" + (beat + 1) + " / " + beatLine.length());

        // The one who is NOT talking goes dark. This is the oldest trick in the
        // form and it does more for readability than any amount of animation.
        for (uint i = 0; i < castIds.length() && i < dimEnt.length(); i++)
            Show(dimEnt[i], castIds[i] != who);

        Text_SetContent(lineEnt, beatLine[beat]);
        lineLen = Text_Length(lineEnt);
        Text_RevealTo(lineEnt, 0);
        shown = 0.0f;
        mode = 0;
        HideOptions();
        Set(prompt, "");
    }

    void Finish() {
        mode = 3;
        Speak("", false);
        for (uint i = 0; i < dimEnt.length(); i++) Show(dimEnt[i], false);
        Set(nameplate, "");
        Set(lineEnt, "");
        Set(prompt, "");
        HideOptions();

        // ONE ROW PER CHARACTER, read off the gap to their mark. This is what
        // the meters were for: not a score, a question about whether you read
        // each of them correctly, answered separately for each.
        for (uint i = 0; i < castIds.length() && i < verdictEnt.length(); i++) {
            int b = BandOf(int(i));
            string tag  = b < int(outcomeTags.length())  ? outcomeTags[b]  : "";
            string line = b < int(outcomeLines.length()) ? outcomeLines[b] : "";
            Set(verdictEnt[i], NameOf(castIds[i]) + "   " + tag
                               + "   " + affinity[i] + " against " + 
                               (i < target.length() ? "" + target[i] : "?")
                               + "   " + line);
        }

        string closing = DataAsset_GetString(conversation, "closing");
        Set(closingEnt, closing != "" ? closing : "The evening ends.");
        for (uint i = 0; i < castIds.length(); i++)
            Meta_SetInt(VN_AFFINITY + castIds[i], affinity[i]);
        Meta_Save();

        string next = DataAsset_GetString(conversation, "nextScene");
        if (next != "") Scene_LoadScene(next);
    }

    // ======================================================================
    void OnUpdate(float dt) {
        if (mode == 3) return;

        if (mode == 0) {
            shown += revealRate * dt;
            if (shown >= float(lineLen)) { shown = float(lineLen); Ready(); }
            Text_RevealTo(lineEnt, int(shown));
            if (Advanced()) { shown = float(lineLen); Text_RevealTo(lineEnt, lineLen); Ready(); }
            return;
        }

        if (autoBeat > 0.0f) {
            autoT += dt;
            if (autoT < autoBeat) return;
            autoT = 0.0f;
            if (mode == 2) Answer(autoPick - 1); else Next();
            return;
        }

        if (mode == 2) {
            if (Input_GetKeyDown(Key::Num1)) Answer(0);
            else if (Input_GetKeyDown(Key::Num2)) Answer(1);
            else if (Input_GetKeyDown(Key::Num3)) Answer(2);
            return;
        }
        if (Advanced()) Next();
    }

    // The line has finished arriving. Either there is an answer to give here,
    // or you are just waiting to hear the next one.
    void Ready() {
        Speak("", false);
        asking = ChoiceAt(beat);
        if (asking >= 0) {
            mode = 2;
            ShowOptions(asking);
            Set(prompt, "1 / 2 / 3 to answer");
        } else {
            mode = 1;
            Set(prompt, "space to continue");
        }
    }

    void Next() {
        // An answer that came with its own reply line plays as its own beat,
        // spoken by whoever the choice was aimed at.
        if (pendingReply != "") {
            string who = asking >= 0 && asking < int(choiceWho.length())
                       ? choiceWho[asking] : "";
            Set(nameplate, NameOf(who));
            Text_SetContent(lineEnt, pendingReply);
            lineLen = Text_Length(lineEnt);
            Text_RevealTo(lineEnt, 0);
            shown = 0.0f;
            mode = 0;
            pendingReply = "";
            asking = -1;
            Speak(who, true);
            return;
        }
        beat++;
        Beat();
    }

    // ======================================================================
    // THE SEAM. The option carries a tag; the table turns it into a face and a
    // number. This script never learns what "warm" or "cool" mean.
    void Answer(int opt) {
        if (asking < 0 || opt < 0) return;
        array<string> tags = Split(Get(choiceTags, asking), ";");
        if (opt >= int(tags.length())) return;

        string tag = tags[opt];
        string who = Get(choiceWho, asking);
        int    idx = IndexOfCast(who);

        // SPEND THE CHOICE. The answering line plays as its own beat WITHOUT
        // advancing `beat`, so without this the beat still carries its choice
        // and Ready() offers the same question again the moment the reply
        // finishes. It reads as one question you can never stop answering, and
        // the meter climbs to full on a single line.
        beatChoice[beat] = "";

        if (idx >= 0) {
            affinity[idx] += int(rx.Delta(tag));
            if (affinity[idx] < 0) affinity[idx] = 0;
            if (affinity[idx] > maxAffinity) affinity[idx] = maxAffinity;
            DrawMeters();
        }
        FireEmote(who, rx.Emote(tag));
        Debug_Log("VNScene: tag '" + tag + "' -> " + who + " affinity "
                  + (idx >= 0 ? "" + affinity[idx] : "?") + " face " + rx.Emote(tag));

        array<string> replies = Split(Get(choiceReply, asking), ";");
        pendingReply = opt < int(replies.length()) ? replies[opt] : "";

        HideOptions();
        Set(prompt, "space to continue");
        mode = 1;
        if (autoBeat > 0.0f) autoT = 0.0f;
    }

    int ChoiceAt(int b) {
        if (b >= int(beatChoice.length())) return -1;
        if (beatChoice[b] == "") return -1;
        int g = ToInt(beatChoice[b]);
        return g >= 0 && g < int(choiceText.length()) ? g : -1;
    }

    void ShowOptions(int group) {
        array<string> opts  = Split(Get(choiceText, group), ";");
        array<string> notes = Split(Get(choiceNote, group), ";");
        for (uint i = 0; i < optEnt.length(); i++) {
            Set(optEnt[i], i < opts.length() ? ("" + (i + 1) + "   " + opts[i]) : "");
            if (i < noteEnt.length())
                Set(noteEnt[i], i < notes.length() ? notes[i] : "");
        }
    }

    void HideOptions() {
        for (uint i = 0; i < optEnt.length(); i++) Set(optEnt[i], "");
        for (uint i = 0; i < noteEnt.length(); i++) Set(noteEnt[i], "");
    }

    // ---- the target mark -------------------------------------------------
    // Where this character expects to be left, as a tick on their own meter.
    // Without it a meter is a number going up, which says nothing about whether
    // you are playing well; the GAP is the reading, and it is why more is not
    // automatically better.
    void PlaceMarks() {
        for (uint i = 0; i < markEnt.length(); i++) {
            if (markEnt[i] == 0) continue;
            if (i >= target.length() || maxAffinity <= 0) { Show(markEnt[i], false); continue; }
            float f = float(target[i]) / float(maxAffinity);
)ENJIN_API"
R"ENJIN_API(            Vector3 p = Entity_GetPosition(markEnt[i]);
            Vector3 s = Entity_GetScale(fillEnt[i]);
            // fillEnt starts at the track's left edge, so that is the origin the
            // mark measures from too.
            float left = Entity_GetPosition(fillEnt[i]).x - s.x * 0.5f;
            Entity_SetPosition(markEnt[i], Vector3(left + meterWidth * f, p.y, p.z));
            Show(markEnt[i], true);
        }
    }

    // Which outcome band the gap to the mark falls in. Symmetric on purpose:
    // overshooting someone is its own kind of misread, not a better result.
    int BandOf(int idx) {
        if (idx < 0 || idx >= int(target.length())) return 2;
        int gap = affinity[idx] - target[idx];
        if (gap <= -8) return 0;
        if (gap <= -3) return 1;
        if (gap <   3) return 2;
        if (gap <   8) return 3;
        return 4;
    }

    array<int> Ints(const string &in joined) {
        // 'out' is a RESERVED KEYWORD in AngelScript and cannot name a local.
        array<int> vals;
        array<string> parts = Split(joined, ";");
        for (uint i = 0; i < parts.length(); i++) vals.insertLast(ToInt(parts[i]));
        return vals;
    }

    void DrawMeters() {
        for (uint i = 0; i < affinity.length() && i < fillEnt.length(); i++) {
            if (fillEnt[i] == 0) continue;
            float f = maxAffinity > 0 ? float(affinity[i]) / float(maxAffinity) : 0.0f;
            Vector3 s = Entity_GetScale(fillEnt[i]);
            Vector3 p = Entity_GetPosition(fillEnt[i]);
            // The bar grows from its left edge, so the centre has to move with
            // the width. Anchoring it at the middle makes it grow both ways.
            float w = meterWidth * f;
            float left = p.x - s.x * 0.5f;
            Entity_SetScale(fillEnt[i], Vector3(w > 0.001f ? w : 0.001f, s.y, s.z));
            Entity_SetPosition(fillEnt[i], Vector3(left + w * 0.5f, p.y, p.z));
            if (i < meterVal.length()) Set(meterVal[i], "" + affinity[i]);
        }
    }

    // ======================================================================
    // Helpers. Every one tolerates a missing entity or a short array, because a
    // template gets cut down and should degrade instead of failing.
    string Get(const array<string> &in a, int i) {
        return i >= 0 && i < int(a.length()) ? a[i] : "";
    }

    int IndexOfCast(const string &in id) {
        for (uint i = 0; i < castIds.length(); i++)
            if (castIds[i] == id) return int(i);
        return -1;
    }

    string NameOf(const string &in id) {
        int i = IndexOfCast(id);
        return i >= 0 && i < int(castNames.length()) ? castNames[i] : id;
    }

    void FireEmote(const string &in who, const string &in emote) {
        if (who == "") return;
        EventData@ d = EventData();
        d.SetString("who", who);
        d.SetString("emote", emote);
        Events_Send("portrait_emote", d);
    }

    void Speak(const string &in who, bool on) {
        EventData@ d = EventData();
        d.SetString("who", who);
        d.SetInt("on", on ? 1 : 0);
        Events_Send("portrait_speak", d);
    }

    bool Advanced() {
        if (autoBeat > 0.0f) return false;
        return Input_GetKeyDown(Key::Space) || Input_GetKeyDown(Key::Enter)
            || Input_GetMouseButtonDown(0);
    }

    void Set(uint64 e, const string &in s) {
        if (e != 0) Text_SetContent(e, s);
    }

    void Show(uint64 e, bool on) {
        if (e != 0) Entity_SetVisible(e, on);
    }

    // Private, not global: a shared file must not introduce a global that
    // collides with a host script's member. See enjin_api/StrUtil.as.
    array<string> Split(const string &in s, const string &in sep) {
        array<string> parts;
        if (sep.length() == 0) { parts.insertLast(s); return parts; }
        int start = 0;
        while (true) {
            int at = s.findFirst(sep, uint(start));
            if (at < 0) {
                parts.insertLast(s.substr(uint(start), s.length() - uint(start)));
                break;
            }
            parts.insertLast(s.substr(uint(start), uint(at - start)));
            start = at + int(sep.length());
        }
        return parts;
    }

    int VnDigit(const string &in c) {
        string digits = "0123456789";
        for (uint i = 0; i < 10; i++) if (digits.substr(i, 1) == c) return int(i);
        return -1;
    }

    int ToInt(const string &in s) {
        int v = 0; bool neg = false, any = false;
        for (uint i = 0; i < s.length(); i++) {
            string c = s.substr(i, 1);
            if (i == 0 && c == "-") { neg = true; continue; }
            int d = VnDigit(c);
            if (d < 0) continue;
            v = v * 10 + d; any = true;
        }
        if (!any) return 0;
        return neg ? -v : v;
    }
}
)ENJIN_API"
;

const char* GetEmbeddedApiSource(const char* name) {
    if (std::strcmp(name, "CineSuite.as") == 0) return s_Api0;
    if (std::strcmp(name, "Math.as") == 0) return s_Api1;
    if (std::strcmp(name, "PortraitRig.as") == 0) return s_Api2;
    if (std::strcmp(name, "Reactions.as") == 0) return s_Api3;
    if (std::strcmp(name, "StateMachine.as") == 0) return s_Api4;
    if (std::strcmp(name, "StrUtil.as") == 0) return s_Api5;
    if (std::strcmp(name, "TegeBehavior.as") == 0) return s_Api6;
    if (std::strcmp(name, "Timer.as") == 0) return s_Api7;
    if (std::strcmp(name, "Tween.as") == 0) return s_Api8;
    if (std::strcmp(name, "VNScene.as") == 0) return s_Api9;
    return nullptr;
}

// Back-compat name used by ScriptEngine for base-class injection
const char* GetEmbeddedTegeBehaviorSource() {
    return GetEmbeddedApiSource("TegeBehavior.as");
}

} // namespace Scripting
} // namespace Enjin
