// GENERATED by _gen_api.py from enjin_api/*.as - DO NOT EDIT BY HAND.
//
// The enjin_api script headers (TegeBehavior base class, Timer, Tween,
// Math, StateMachine) are embedded in the engine so game scripts always
// compile - no per-project copies required. On-disk enjin_api files, when
// present, override these copies (modding / engine development).
#include <cstring>

namespace Enjin {
namespace Scripting {

static const char* s_Api0 = R"ENJIN_API(
// Math utility functions for TegeBehavior scripts
// These wrap the engine's registered global math functions.

// Note: Vector2, Vector3, Vector4, Quaternion are registered as native types
// by the engine. The following are convenience functions.

// Linearly interpolate between two Vector3 values
Vector3 LerpVector3(const Vector3 &in a, const Vector3 &in b, float t) {
    return Vector3(
        Lerp(a.x, b.x, t),
        Lerp(a.y, b.y, t),
        Lerp(a.z, b.z, t)
    );
}

// Move a Vector3 toward a target, capped by maxDelta
Vector3 MoveTowardsVector3(const Vector3 &in current, const Vector3 &in target, float maxDelta) {
    Vector3 diff = target - current;
    float dist = diff.Length();
    if (dist <= maxDelta || dist < 0.0001f) {
        return target;
    }
    return current + diff * (maxDelta / dist);
}

// Distance between two points
float Distance(const Vector3 &in a, const Vector3 &in b) {
    return (b - a).Length();
}

// Direction from a to b (normalized)
Vector3 Direction(const Vector3 &in from, const Vector3 &in to) {
    return (to - from).Normalized();
}

// Convert degrees to radians
float Deg2Rad(float degrees) {
    return degrees * 3.14159265f / 180.0f;
}

// Convert radians to degrees
float Rad2Deg(float radians) {
    return radians * 180.0f / 3.14159265f;
}
)ENJIN_API";

static const char* s_Api1 = R"ENJIN_API(
// StateMachine.as — Simple finite state machine for game logic
// Usage:
//   class EnemyAI : TegeBehavior {
//       StateMachine fsm;
//
//       void OnStart() {
//           fsm.AddState("idle");
//           fsm.AddState("chase");
//           fsm.AddState("attack");
//           fsm.SetState("idle");
//       }
//
//       void OnUpdate(float dt) {
//           fsm.Update(dt);
//
//           if (fsm.IsState("idle")) {
//               // idle logic
//               if (playerNearby) fsm.SetState("chase");
//           } else if (fsm.IsState("chase")) {
//               // chase logic
//               if (inRange) fsm.SetState("attack");
//           }
//       }
//   }

class StateMachine {
    private string currentState;
    private string previousState;
    private float stateTime;
    private array<string> states;

    StateMachine() {
        stateTime = 0.0f;
    }

    // Add a named state
    void AddState(const string &in name) {
        states.insertLast(name);
    }

    // Transition to a new state
    void SetState(const string &in name) {
        if (currentState == name) return;
        previousState = currentState;
        currentState = name;
        stateTime = 0.0f;
    }

    // Get the current state name
    string GetState() const {
        return currentState;
    }

    // Get the previous state name
    string GetPreviousState() const {
        return previousState;
    }

    // Check if currently in a specific state
    bool IsState(const string &in name) const {
        return currentState == name;
    }

    // Check if just entered this state (first frame)
    bool JustEntered(const string &in name) const {
        return currentState == name && stateTime == 0.0f;
    }

    // Get time spent in current state (seconds)
    float GetStateTime() const {
        return stateTime;
    }

    // Check if a state exists
    bool HasState(const string &in name) const {
        for (uint i = 0; i < states.length(); i++) {
            if (states[i] == name) return true;
        }
        return false;
    }

    // Get number of registered states
    uint GetStateCount() const {
        return states.length();
    }

    // Call each frame to track time in state
    void Update(float dt) {
        stateTime += dt;
    }

    // Reset to no state
    void Reset() {
        previousState = currentState;
        currentState = "";
        stateTime = 0.0f;
    }
}
)ENJIN_API";

static const char* s_Api2 = R"ENJIN_API(
// TegeBehavior — base class for all game scripts
// Inherit from this class to attach behavior to entities.
//
// Example:
//   class PlayerController : TegeBehavior {
//       [Property] float moveSpeed = 5.0f;
//
//       void OnUpdate(float dt) {
//           Vector3 move = Vector3(0, 0, 0);
//           if (Input_GetKey(Key::W)) move.z -= 1;
//           if (Input_GetKey(Key::S)) move.z += 1;
//           move = move.Normalized() * moveSpeed;
//           SetPosition(GetPosition() + move * dt);
//       }
//   }

class TegeBehavior {
    // Entity this behavior is attached to (set by the engine)
    uint64 _entityId;

    // Whether this behavior is enabled
    bool enabled = true;

    // --- Transform shortcuts ---

    Vector3 GetPosition() {
        return Entity_GetPosition(_entityId);
    }

    void SetPosition(const Vector3 &in pos) {
        Entity_SetPosition(_entityId, pos);
    }

    Vector3 GetRotation() {
        return Entity_GetRotation(_entityId);
    }

    void SetRotation(const Vector3 &in rot) {
        Entity_SetRotation(_entityId, rot);
    }

    Vector3 GetScale() {
        return Entity_GetScale(_entityId);
    }

    void SetScale(const Vector3 &in s) {
        Entity_SetScale(_entityId, s);
    }

    string GetName() {
        return Entity_GetName(_entityId);
    }

    uint64 GetEntity() {
        return _entityId;
    }

    // --- Coroutines ---

    void StartCoroutine(const string &in funcName) {
        ::StartCoroutine(funcName);
    }

    // --- Lifecycle callbacks (override in subclasses) ---
    // void OnCreate()                { }
    // void OnStart()                 { }
    // void OnUpdate(float dt)        { }
    // void OnFixedUpdate(float dt)   { }
    // void OnLateUpdate(float dt)    { }
    // void OnDestroy()               { }
    // void OnEnable()                { }
    // void OnDisable()               { }
    // void OnCollisionEnter(uint64 other) { }
    // void OnCollisionStay(uint64 other)  { }
    // void OnCollisionExit(uint64 other)  { }
    // void OnTriggerEnter(uint64 other)   { }
    // void OnTriggerExit(uint64 other)    { }
}
)ENJIN_API";

static const char* s_Api3 = R"ENJIN_API(
// Timer.as — Countdown and repeating timer utility
// Usage:
//   class Spawner : TegeBehavior {
//       Timer spawnTimer;
//
//       void OnStart() {
//           spawnTimer.Start(2.0f, true); // 2 seconds, repeating
//       }
//
//       void OnUpdate(float dt) {
//           spawnTimer.Update(dt);
//           if (spawnTimer.JustFinished()) {
//               SpawnEnemy();
//           }
//       }
//   }

class Timer {
    private float duration;
    private float elapsed;
    private bool running;
    private bool repeating;
    private bool finished;
    private bool justFinishedFlag;
    private int repeatCount;
    private int maxRepeats; // -1 = infinite

    Timer() {
        duration = 0.0f;
        elapsed = 0.0f;
        running = false;
        repeating = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
        maxRepeats = -1;
    }

    // Start a one-shot timer
    void Start(float dur) {
        duration = dur;
        elapsed = 0.0f;
        running = true;
        repeating = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
        maxRepeats = -1;
    }

    // Start a repeating timer
    void Start(float dur, bool repeat) {
        Start(dur);
        repeating = repeat;
    }

    // Start a repeating timer with max repeat count
    void Start(float dur, bool repeat, int maxReps) {
        Start(dur);
        repeating = repeat;
        maxRepeats = maxReps;
    }

    // Stop the timer
    void Stop() {
        running = false;
    }

    // Resume a stopped timer
    void Resume() {
        if (!finished) running = true;
    }

    // Reset and stop
    void Reset() {
        elapsed = 0.0f;
        running = false;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
    }

    // Reset and immediately restart
    void Restart() {
        elapsed = 0.0f;
        running = true;
        finished = false;
        justFinishedFlag = false;
        repeatCount = 0;
    }

    // Call every frame
    void Update(float dt) {
        justFinishedFlag = false;
        if (!running || finished) return;

        elapsed += dt;
        if (elapsed >= duration) {
            justFinishedFlag = true;
            repeatCount++;

            if (repeating) {
                if (maxRepeats >= 0 && repeatCount >= maxRepeats) {
                    finished = true;
                    running = false;
                } else {
                    // Carry over excess time for accurate repeating
                    elapsed -= duration;
                }
            } else {
                finished = true;
                running = false;
                elapsed = duration;
            }
        }
    }

    // True only on the frame the timer completes (or each repeat cycle)
    bool JustFinished() const {
        return justFinishedFlag;
    }

    // True if the timer has completed (and is not repeating, or max repeats reached)
    bool IsFinished() const {
        return finished;
    }

    // True if the timer is actively counting
    bool IsRunning() const {
        return running;
    }

    // Progress from 0 to 1
    float GetProgress() const {
        if (duration <= 0.0f) return 1.0f;
        return Clamp(elapsed / duration, 0.0f, 1.0f);
    }

    // Time remaining
    float GetRemaining() const {
        float r = duration - elapsed;
        if (r < 0.0f) return 0.0f;
        return r;
    }

    // Time elapsed in current cycle
    float GetElapsed() const {
        return elapsed;
    }

    // Total duration
    float GetDuration() const {
        return duration;
    }

    // Number of times the timer has completed
    int GetRepeatCount() const {
        return repeatCount;
    }
}
)ENJIN_API";

static const char* s_Api4 = R"ENJIN_API(
// Tween.as — Easing and interpolation utilities for TegeBehavior scripts
// Usage:
//   float t = Tween::EaseInOut(elapsed / duration);
//   SetPosition(LerpVector3(startPos, endPos, t));

// Easing functions — all take t in [0,1] and return [0,1]
namespace Tween {

// Linear (no easing)
float Linear(float t) {
    return t;
}

// Quadratic
float EaseInQuad(float t) {
    return t * t;
}
float EaseOutQuad(float t) {
    return t * (2.0f - t);
}
float EaseInOutQuad(float t) {
    if (t < 0.5f) return 2.0f * t * t;
    return -1.0f + (4.0f - 2.0f * t) * t;
}

// Cubic
float EaseInCubic(float t) {
    return t * t * t;
}
float EaseOutCubic(float t) {
    float u = t - 1.0f;
    return u * u * u + 1.0f;
}
float EaseInOutCubic(float t) {
    if (t < 0.5f) return 4.0f * t * t * t;
    float u = 2.0f * t - 2.0f;
    return 0.5f * u * u * u + 1.0f;
}

// Quartic
float EaseInQuart(float t) {
    return t * t * t * t;
}
float EaseOutQuart(float t) {
    float u = t - 1.0f;
    return 1.0f - u * u * u * u;
}
float EaseInOutQuart(float t) {
    if (t < 0.5f) return 8.0f * t * t * t * t;
    float u = t - 1.0f;
    return 1.0f - 8.0f * u * u * u * u;
}

// Sine
float EaseInSine(float t) {
    return 1.0f - Cos(t * 3.14159265f * 0.5f);
}
float EaseOutSine(float t) {
    return Sin(t * 3.14159265f * 0.5f);
}
float EaseInOutSine(float t) {
    return 0.5f * (1.0f - Cos(3.14159265f * t));
}

// Exponential
float EaseInExpo(float t) {
    if (t <= 0.0f) return 0.0f;
    return Pow(2.0f, 10.0f * (t - 1.0f));
}
float EaseOutExpo(float t) {
    if (t >= 1.0f) return 1.0f;
    return 1.0f - Pow(2.0f, -10.0f * t);
}
float EaseInOutExpo(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    if (t < 0.5f) return 0.5f * Pow(2.0f, 20.0f * t - 10.0f);
    return 1.0f - 0.5f * Pow(2.0f, -20.0f * t + 10.0f);
}

// Back (overshoot)
float EaseInBack(float t) {
    float s = 1.70158f;
    return t * t * ((s + 1.0f) * t - s);
}
float EaseOutBack(float t) {
    float s = 1.70158f;
    float u = t - 1.0f;
    return u * u * ((s + 1.0f) * u + s) + 1.0f;
}
float EaseInOutBack(float t) {
    float s = 1.70158f * 1.525f;
    if (t < 0.5f) {
        float u = 2.0f * t;
        return 0.5f * (u * u * ((s + 1.0f) * u - s));
    }
    float u = 2.0f * t - 2.0f;
    return 0.5f * (u * u * ((s + 1.0f) * u + s) + 2.0f);
}

// Elastic
float EaseInElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    return -Pow(2.0f, 10.0f * t - 10.0f) * Sin((t * 10.0f - 10.75f) * (2.0f * 3.14159265f / 3.0f));
}
float EaseOutElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    return Pow(2.0f, -10.0f * t) * Sin((t * 10.0f - 0.75f) * (2.0f * 3.14159265f / 3.0f)) + 1.0f;
}
float EaseInOutElastic(float t) {
    if (t <= 0.0f) return 0.0f;
    if (t >= 1.0f) return 1.0f;
    float c = (2.0f * 3.14159265f) / 4.5f;
    if (t < 0.5f)
        return -0.5f * Pow(2.0f, 20.0f * t - 10.0f) * Sin((20.0f * t - 11.125f) * c);
    return 0.5f * Pow(2.0f, -20.0f * t + 10.0f) * Sin((20.0f * t - 11.125f) * c) + 1.0f;
}

// Bounce
float EaseOutBounce(float t) {
    if (t < 1.0f / 2.75f) {
        return 7.5625f * t * t;
    } else if (t < 2.0f / 2.75f) {
        float u = t - 1.5f / 2.75f;
        return 7.5625f * u * u + 0.75f;
    } else if (t < 2.5f / 2.75f) {
        float u = t - 2.25f / 2.75f;
        return 7.5625f * u * u + 0.9375f;
    } else {
        float u = t - 2.625f / 2.75f;
        return 7.5625f * u * u + 0.984375f;
    }
}
float EaseInBounce(float t) {
    return 1.0f - EaseOutBounce(1.0f - t);
}
float EaseInOutBounce(float t) {
    if (t < 0.5f) return 0.5f * EaseInBounce(2.0f * t);
    return 0.5f * EaseOutBounce(2.0f * t - 1.0f) + 0.5f;
}

// Convenience aliases
float EaseIn(float t)    { return EaseInCubic(t); }
float EaseOut(float t)   { return EaseOutCubic(t); }
float EaseInOut(float t) { return EaseInOutCubic(t); }

} // namespace Tween

// Interpolation helpers using easing
float TweenFloat(float from, float to, float t) {
    return from + (to - from) * t;
}

Vector3 TweenVector3(const Vector3 &in from, const Vector3 &in to, float t) {
    return LerpVector3(from, to, t);
}
)ENJIN_API";

const char* GetEmbeddedApiSource(const char* name) {
    if (std::strcmp(name, "Math.as") == 0) return s_Api0;
    if (std::strcmp(name, "StateMachine.as") == 0) return s_Api1;
    if (std::strcmp(name, "TegeBehavior.as") == 0) return s_Api2;
    if (std::strcmp(name, "Timer.as") == 0) return s_Api3;
    if (std::strcmp(name, "Tween.as") == 0) return s_Api4;
    return nullptr;
}

// Back-compat name used by ScriptEngine for base-class injection
const char* GetEmbeddedTegeBehaviorSource() {
    return GetEmbeddedApiSource("TegeBehavior.as");
}

} // namespace Scripting
} // namespace Enjin
