#!/usr/bin/env python3
"""Fail when an RT shader source changed without _gen_rt.py being re-run.

RTShaderData.h is a 660KB generated file that is TRACKED in git, and every ray
tracing subsystem reads its SPIR-V straight out of that header - nothing loads
rt_*.spv from disk. The header is regenerated by _gen_rt.py, which is invoked
by nothing: not CMake (its codegen glob is .vert/.frag/.comp and explicitly
excludes /rt_), not CI. It stays correct purely because somebody remembers.

Edit an rt_ shader, forget the script, and the engine runs stale SPIR-V against
current source. The GLSL on disk looks right, the GPU reads different bytes,
and nothing anywhere says so. That is the same failure class as the
PostProcessing fossil that hid for months, and the CLAUDE.md warning about
stale SPIR-V exists because of it.

So _gen_rt.py stamps a SOURCE-SHA256 of the shader sources into the header, and
this recomputes it.

    python tools/rt_shader_freshness.py

Why a source hash and not a diff of the regenerated header: the header's bytes
depend on the exact glslc version that produced them. A byte-diff would go red
every time the Vulkan SDK moves, which is noise, and it would need glslc in CI,
which is not installed. Hashing the INPUTS goes red only when a shader source
actually changed without a regeneration, which is the thing worth catching.

What this does NOT catch: a header generated from the right sources with the
wrong compiler flags, or hand-edited SPIR-V. It answers one question - were
these sources the ones this header was built from - and that is the question
that has an actual failure mode behind it.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "Engine", "shaders")
HEADER = os.path.join(ROOT, "Engine", "include", "Enjin", "Renderer",
                      "RayTracing", "RTShaderData.h")

# Kept in step with _gen_rt.py by construction: the source list is parsed out of
# _gen_rt.py's own tables rather than duplicated here, so adding a shader there
# cannot leave this checker behind.
ARRAY_RE = re.compile(r"^static const uint32_t ([A-Z0-9_]+)\[\]", re.M)
STAMP_RE = re.compile(r"^// SOURCE-SHA256: ([0-9a-f]{64})\s*$", re.M)


def source_files():
    """The .spv names _gen_rt.py consumes, mapped back to their GLSL sources.

    _gen_rt.py owns the authoritative list, so read it from there rather than
    restating it here, and the two cannot drift apart.
    """
    # _gen_rt.py writes files as a side effect of import, so read its tables
    # textually instead of executing it.
    text = open(os.path.join(ROOT, "_gen_rt.py"), encoding="utf-8").read()
    names = set(re.findall(r'\("([^"]+\.spv)"', text))
    out = set(n[:-4] for n in names)
    for f in os.listdir(SHADERS):
        if f.endswith(".glsl"):
            out.add(f)
    return sorted(out)


def source_hash():
    h = hashlib.sha256()
    missing = []
    for n in source_files():
        p = os.path.join(SHADERS, n)
        if not os.path.isfile(p):
            missing.append(n)
            continue
        h.update(n.encode("utf-8"))
        with open(p, "rb") as fh:
            # Must match _gen_rt.py exactly. See the note there: core.autocrlf
            # makes the same committed file CRLF on Windows and LF on Linux, so
            # the hash is taken over normalised content, not raw bytes.
            h.update(fh.read().replace(b"\r\n", b"\n"))
    return h.hexdigest(), missing


def main():
    if not os.path.isfile(HEADER):
        print("FAIL: %s does not exist" % HEADER)
        return 1

    text = open(HEADER, encoding="utf-8", errors="replace").read()
    m = STAMP_RE.search(text)
    if not m:
        print("FAIL: RTShaderData.h carries no SOURCE-SHA256 stamp.")
        print("      Regenerate it: compile the RT shaders with")
        print("      glslc --target-env=vulkan1.2 -I. then run python _gen_rt.py")
        return 1

    recorded = m.group(1)
    actual, missing = source_hash()

    if missing:
        print("FAIL: %d shader source(s) named by _gen_rt.py are missing:" % len(missing))
        for n in missing:
            print("        Engine/shaders/%s" % n)
        return 1

    arrays = len(ARRAY_RE.findall(text))
    print("RT shader freshness")
    print("  embedded arrays : %d" % arrays)
    print("  sources hashed  : %d" % len(source_files()))
    print("  recorded        : %s" % recorded)
    print("  actual          : %s" % actual)

    if recorded != actual:
        print("")
        print("FAIL: an RT shader source changed but RTShaderData.h was not")
        print("      regenerated, so the engine is compiled against stale SPIR-V.")
        print("      Fix:")
        print("        cd Engine/shaders")
        print("        glslc --target-env=vulkan1.2 -I. <changed shader> -o <shader>.spv")
        print("        cd ../.. && python _gen_rt.py")
        print("      then commit the regenerated header.")
        return 1

    print("\n  OK: header matches its sources.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
