#include "EnjinTest.h"
#include "Enjin/ECS/Components/LOD.h"

using namespace Enjin;
using namespace Enjin::ECS;

// ===========================================================================
// LODComponent Defaults
// ===========================================================================

ENJIN_TEST(LODDefaults, MaxLevels) {
    ENJIN_EXPECT_EQ(LODComponent::MAX_LEVELS, 5);
}

ENJIN_TEST(LODDefaults, InitialState) {
    LODComponent lod;
    ENJIN_EXPECT_EQ(lod.levelCount, 0);
    ENJIN_EXPECT_EQ(lod.activeLOD, 0);
    ENJIN_EXPECT_TRUE(lod.enabled);
    ENJIN_EXPECT_FALSE(lod.autoGenerated);
}

ENJIN_TEST(LODDefaults, DistanceSettings) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.baseDistance, 10.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.distanceMultiplier, 2.0f);
}

ENJIN_TEST(LODDefaults, Hysteresis) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.hysteresisRatio, 0.1f);
}

ENJIN_TEST(LODDefaults, UseScreenSize) {
    LODComponent lod;
    ENJIN_EXPECT_TRUE(lod.useScreenSize);
}

ENJIN_TEST(LODDefaults, ReductionRatios) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[0], 1.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[1], 0.5f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[2], 0.25f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[3], 0.12f);
    ENJIN_EXPECT_FLOAT_NEAR(lod.reductionRatios[4], 0.06f, 0.001f);
}

// ===========================================================================
// LODLevel Defaults
// ===========================================================================

ENJIN_TEST(LODLevel, DefaultLevel) {
    LODComponent::LODLevel level;
    ENJIN_EXPECT_FLOAT_EQ(level.maxDistance, 0.0f);
    ENJIN_EXPECT_EQ(level.vertexCount, 0u);
    ENJIN_EXPECT_EQ(level.triangleCount, 0u);
    ENJIN_EXPECT_FLOAT_EQ(level.reductionRatio, 1.0f);
}

// ===========================================================================
// Configuration
// ===========================================================================

ENJIN_TEST(LODConfig, SetLevels) {
    LODComponent lod;
    lod.levelCount = 3;
    lod.levels[0].maxDistance = 10.0f;
    lod.levels[0].reductionRatio = 1.0f;
    lod.levels[1].maxDistance = 25.0f;
    lod.levels[1].reductionRatio = 0.5f;
    lod.levels[2].maxDistance = 50.0f;
    lod.levels[2].reductionRatio = 0.25f;

    ENJIN_EXPECT_EQ(lod.levelCount, 3);
    ENJIN_EXPECT_FLOAT_EQ(lod.levels[1].maxDistance, 25.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.levels[2].reductionRatio, 0.25f);
}

ENJIN_TEST(LODConfig, DisableLOD) {
    LODComponent lod;
    lod.enabled = false;
    ENJIN_EXPECT_FALSE(lod.enabled);
}

// ===========================================================================
// LOD selection (ECS::SelectLOD) — the real engine function, shared by both
// RenderSystem LOD paths. These replace earlier tests that recomputed the
// distance/hysteresis arithmetic in the test body.
// ===========================================================================

namespace {
LODComponent ThreeLevelLOD() {
    LODComponent lod;
    lod.levelCount = 3;
    lod.levels[0].maxDistance = 10.0f;
    lod.levels[1].maxDistance = 25.0f;
    lod.levels[2].maxDistance = 50.0f;
    lod.hysteresisRatio = 0.1f;  // band = 1.0 at threshold 10
    return lod;
}
} // namespace

ENJIN_TEST(LODSelect, StaysHighDetailWhenClose) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 1.0f), 0);  // very close -> full detail
}

ENJIN_TEST(LODSelect, DowngradesWithDistance) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 15.0f), 1);  // past level 0 band (>11)
    ENJIN_EXPECT_EQ(SelectLOD(lod, 40.0f), 2);  // past level 1 band (>27.5)
}

ENJIN_TEST(LODSelect, HysteresisDeadZoneHoldsLevel) {
    LODComponent lod = ThreeLevelLOD();
    // At LOD 0, just past threshold 10 but inside the +band (11) -> no downgrade.
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 10.5f), 0);
    // At LOD 1, just under threshold 10 but inside the -band (9) -> no upgrade.
    lod.activeLOD = 1;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 9.5f), 1);
}

ENJIN_TEST(LODSelect, UpgradesWhenWellInside) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 2;
    // Move close enough to clear level 1's lower band (25 - 2.5 = 22.5) and
    // level 0's lower band (10 - 1 = 9) -> back to full detail.
    ENJIN_EXPECT_EQ(SelectLOD(lod, 5.0f), 0);
}

ENJIN_TEST(LODSelect, SingleLevelNeverSwitches) {
    LODComponent lod;
    lod.levelCount = 1;
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 9999.0f), 0);
}

ENJIN_TEST(LODSelect, ThresholdFallbackUsesBaseDistance) {
    // maxDistance unset (0) -> falls back to baseDistance * mult^level (10, 20).
    LODComponent lod;
    lod.levelCount = 3;
    lod.baseDistance = 10.0f;
    lod.distanceMultiplier = 2.0f;
    lod.hysteresisRatio = 0.1f;
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 5.0f), 0);   // inside fallback threshold 10
    ENJIN_EXPECT_EQ(SelectLOD(lod, 30.0f), 2);  // past fallback thresholds 10 and 20
}

ENJIN_TEST_MAIN()
