#include "EnjinTest.h"
#include "Enjin/ECS/Components/LOD.h"

#include <cmath>

using namespace Enjin;
using namespace Enjin::ECS;

// ===========================================================================
// LODComponent Defaults
// ===========================================================================

ENJIN_TEST(LODDefaults, MaxLevels) {
    ENJIN_EXPECT_EQ(LODComponent::MAX_LEVELS, 5);
}

ENJIN_TEST(LODDefaults, InitialState) {
    LODComponent lod;
    ENJIN_EXPECT_EQ(lod.levelCount, 0);
    ENJIN_EXPECT_EQ(lod.activeLOD, 0);
    ENJIN_EXPECT_TRUE(lod.enabled);
    ENJIN_EXPECT_FALSE(lod.autoGenerated);
}

ENJIN_TEST(LODDefaults, DistanceSettings) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.baseDistance, 10.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.distanceMultiplier, 2.0f);
}

ENJIN_TEST(LODDefaults, Hysteresis) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.hysteresisRatio, 0.1f);
}

ENJIN_TEST(LODDefaults, UseScreenSize) {
    LODComponent lod;
    ENJIN_EXPECT_TRUE(lod.useScreenSize);
}

ENJIN_TEST(LODDefaults, ReductionRatios) {
    LODComponent lod;
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[0], 1.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[1], 0.5f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[2], 0.25f);
    ENJIN_EXPECT_FLOAT_EQ(lod.reductionRatios[3], 0.12f);
    ENJIN_EXPECT_FLOAT_NEAR(lod.reductionRatios[4], 0.06f, 0.001f);
}

// ===========================================================================
// LODLevel Defaults
// ===========================================================================

ENJIN_TEST(LODLevel, DefaultLevel) {
    LODComponent::LODLevel level;
    ENJIN_EXPECT_FLOAT_EQ(level.maxDistance, 0.0f);
    ENJIN_EXPECT_EQ(level.vertexCount, 0u);
    ENJIN_EXPECT_EQ(level.triangleCount, 0u);
    ENJIN_EXPECT_FLOAT_EQ(level.reductionRatio, 1.0f);
}

// ===========================================================================
// Configuration
// ===========================================================================

ENJIN_TEST(LODConfig, SetLevels) {
    LODComponent lod;
    lod.levelCount = 3;
    lod.levels[0].maxDistance = 10.0f;
    lod.levels[0].reductionRatio = 1.0f;
    lod.levels[1].maxDistance = 25.0f;
    lod.levels[1].reductionRatio = 0.5f;
    lod.levels[2].maxDistance = 50.0f;
    lod.levels[2].reductionRatio = 0.25f;

    ENJIN_EXPECT_EQ(lod.levelCount, 3);
    ENJIN_EXPECT_FLOAT_EQ(lod.levels[1].maxDistance, 25.0f);
    ENJIN_EXPECT_FLOAT_EQ(lod.levels[2].reductionRatio, 0.25f);
}

ENJIN_TEST(LODConfig, DisableLOD) {
    LODComponent lod;
    lod.enabled = false;
    ENJIN_EXPECT_FALSE(lod.enabled);
}

// ===========================================================================
// LOD selection (ECS::SelectLOD) — the real engine function, shared by both
// RenderSystem LOD paths. These replace earlier tests that recomputed the
// distance/hysteresis arithmetic in the test body.
// ===========================================================================

namespace {
LODComponent ThreeLevelLOD() {
    LODComponent lod;
    lod.levelCount = 3;
    lod.levels[0].maxDistance = 10.0f;
    lod.levels[1].maxDistance = 25.0f;
    lod.levels[2].maxDistance = 50.0f;
    lod.hysteresisRatio = 0.1f;  // band = 1.0 at threshold 10
    return lod;
}
} // namespace

ENJIN_TEST(LODSelect, StaysHighDetailWhenClose) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 1.0f), 0);  // very close -> full detail
}

ENJIN_TEST(LODSelect, DowngradesWithDistance) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 15.0f), 1);  // past level 0 band (>11)
    ENJIN_EXPECT_EQ(SelectLOD(lod, 40.0f), 2);  // past level 1 band (>27.5)
}

ENJIN_TEST(LODSelect, HysteresisDeadZoneHoldsLevel) {
    LODComponent lod = ThreeLevelLOD();
    // At LOD 0, just past threshold 10 but inside the +band (11) -> no downgrade.
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 10.5f), 0);
    // At LOD 1, just under threshold 10 but inside the -band (9) -> no upgrade.
    lod.activeLOD = 1;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 9.5f), 1);
}

ENJIN_TEST(LODSelect, UpgradesWhenWellInside) {
    LODComponent lod = ThreeLevelLOD();
    lod.activeLOD = 2;
    // Move close enough to clear level 1's lower band (25 - 2.5 = 22.5) and
    // level 0's lower band (10 - 1 = 9) -> back to full detail.
    ENJIN_EXPECT_EQ(SelectLOD(lod, 5.0f), 0);
}

ENJIN_TEST(LODSelect, SingleLevelNeverSwitches) {
    LODComponent lod;
    lod.levelCount = 1;
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 9999.0f), 0);
}

ENJIN_TEST(LODSelect, ThresholdFallbackUsesBaseDistance) {
    // maxDistance unset (0) -> falls back to baseDistance * mult^level (10, 20).
    LODComponent lod;
    lod.levelCount = 3;
    lod.baseDistance = 10.0f;
    lod.distanceMultiplier = 2.0f;
    lod.hysteresisRatio = 0.1f;
    lod.activeLOD = 0;
    ENJIN_EXPECT_EQ(SelectLOD(lod, 5.0f), 0);   // inside fallback threshold 10
    ENJIN_EXPECT_EQ(SelectLOD(lod, 30.0f), 2);  // past fallback thresholds 10 and 20
}

// ===========================================================================
// ResolveLODSourceExtent
//
// The metric's denominator. Its unset-AABB case is the one that shipped broken:
// nothing populates MeshComponent::cachedAABB* in a player, so the old fallback read
// the sentinel (min 1,1,1 / max -1,-1,-1), got a NEGATIVE extent, and pinned every
// legacy LOD to its coarsest mesh. These pin the four sources and the refusal.
// ===========================================================================

namespace {
MeshComponent BoxMesh(f32 halfX, f32 halfY, f32 halfZ) {
    MeshComponent m;
    const f32 xs[2] = { -halfX, halfX };
    const f32 ys[2] = { -halfY, halfY };
    const f32 zs[2] = { -halfZ, halfZ };
    for (int i = 0; i < 8; ++i) {
        MeshComponent::Vertex v;
        v.position = Math::Vector3(xs[i & 1], ys[(i >> 1) & 1], zs[(i >> 2) & 1]);
        m.vertices.push_back(v);
    }
    for (u32 i = 0; i < 6; ++i) m.indices.push_back(i);
    return m;
}
} // namespace

ENJIN_TEST(LODExtent, PrefersRecordedSourceExtent) {
    LODComponent lod;
    lod.sourceMaxExtent = 7.0f;
    MeshComponent live = BoxMesh(100.0f, 100.0f, 100.0f);   // must be ignored
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &live), 7.0f);
}

ENJIN_TEST(LODExtent, UnsetAabbDoesNotProduceNegativeExtent) {
    // The shipped bug. A mesh whose AABB was never computed and whose vertices are
    // gone must yield "no idea" (0), never a negative extent.
    LODComponent lod;
    MeshComponent live;                       // no vertices, sentinel AABB
    live.indices.push_back(0);
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &live), 0.0f);
    ENJIN_EXPECT_EQ(lod.sourceMaxExtent, 0.0f);   // nothing invented, nothing cached
}

ENJIN_TEST(LODExtent, ComputesFromVerticesWhenAabbUnset) {
    LODComponent lod;
    MeshComponent live = BoxMesh(1.0f, 3.0f, 2.0f);   // extents 2, 6, 4 -> 6
    ENJIN_EXPECT_TRUE(live.aabbDirty);
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &live), 6.0f);
}

ENJIN_TEST(LODExtent, BackFillsSoTheMetricIsStable) {
    LODComponent lod;
    MeshComponent live = BoxMesh(1.0f, 3.0f, 2.0f);
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &live), 6.0f);
    ENJIN_EXPECT_EQ(lod.sourceMaxExtent, 6.0f);
    // Second call must not depend on the live mesh at all — that dependency is what
    // made the selection feed back on itself and flicker.
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, nullptr), 6.0f);
}

ENJIN_TEST(LODExtent, PrefersLevelZeroOverTheSwappedLiveMesh) {
    // Mid-swap the live mesh IS a coarse level. Measuring it would move the metric
    // that chose it.
    LODComponent lod;
    lod.levelCount = 2;
    lod.levels[0].mesh = BoxMesh(5.0f, 5.0f, 5.0f);    // original, extent 10
    MeshComponent live = BoxMesh(0.5f, 0.5f, 0.5f);    // swapped-in coarse level
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &live), 10.0f);
}

ENJIN_TEST(LODExtent, NoMeshAtAllIsZeroNotAGuess) {
    LODComponent lod;
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, nullptr), 0.0f);
}

ENJIN_TEST(LODExtent, DegenerateMeshIsZeroNotAGuess) {
    LODComponent lod;
    MeshComponent flat = BoxMesh(0.0f, 0.0f, 0.0f);   // every vertex coincident
    ENJIN_EXPECT_EQ(ResolveLODSourceExtent(lod, &flat), 0.0f);
}

// ===========================================================================
// The governor's global LOD scale
//
// AdaptiveQualitySystem has computed a LOD bias since it was written and NOTHING
// read it: GetRecommendedLODBias and its adjustLODBias flag had zero callers, so the
// frame-rate governor scaled shadow quality under load and never touched LOD.
//
// It is applied to the METRIC, so these pin the arithmetic that RenderSystem does
// rather than reaching into the renderer: scale > 1 means transitions further away
// and MORE detail, which is the OPPOSITE convention to MeshRenderer::lodBias, and
// the two being opposite is exactly the kind of thing a test should hold still.
// ===========================================================================

namespace {
// What ChooseLOD does with the two biases, in one place.
f32 BiasedMetric(f32 metric, f32 meshRendererBias, f32 adaptiveScale) {
    f32 m = metric;
    if (meshRendererBias != 0.0f) m *= std::pow(2.0f, meshRendererBias);
    if (adaptiveScale != 1.0f) m /= adaptiveScale;
    return m;
}
}  // namespace

ENJIN_TEST(LODAdaptiveScale, test_scale_of_one_leaves_the_metric_alone) {
    // Arrange / Act / Assert — the default must be exactly inert, or every project
    // that never touches quality settings silently re-LODs.
    ENJIN_EXPECT_FLOAT_EQ(BiasedMetric(20.0f, 0.0f, 1.0f), 20.0f);
}

ENJIN_TEST(LODAdaptiveScale, test_higher_scale_means_more_detail) {
    // Ultra is 1.5: the metric shrinks, so an object sits in a nearer band and keeps
    // a finer mesh.
    const f32 ultra = BiasedMetric(30.0f, 0.0f, 1.5f);
    ENJIN_EXPECT_TRUE(ultra < 30.0f);
    ENJIN_EXPECT_FLOAT_EQ(ultra, 20.0f);
}

ENJIN_TEST(LODAdaptiveScale, test_lower_scale_means_less_detail) {
    // VeryLow is 0.5: the metric doubles and everything drops a level sooner, which
    // is the whole point of the governor reaching LOD at all.
    ENJIN_EXPECT_FLOAT_EQ(BiasedMetric(30.0f, 0.0f, 0.5f), 60.0f);
}

ENJIN_TEST(LODAdaptiveScale, test_the_two_biases_run_in_opposite_directions) {
    // MeshRenderer::lodBias: POSITIVE means lower detail (metric grows).
    // The governor's scale: HIGHER means more detail (metric shrinks).
    // Opposite by design -- one is what the author asked for, the other is what the
    // machine can afford -- so a change that quietly aligned them would be wrong.
    ENJIN_EXPECT_TRUE(BiasedMetric(10.0f, 1.0f, 1.0f) > 10.0f);
    ENJIN_EXPECT_TRUE(BiasedMetric(10.0f, 0.0f, 1.5f) < 10.0f);
}

ENJIN_TEST(LODAdaptiveScale, test_author_bias_and_governor_scale_compose) {
    // An entity forced toward detail by its author, on a machine the governor has
    // turned down: both apply, neither wins outright.
    const f32 m = BiasedMetric(16.0f, -1.0f, 0.5f);   // halve, then double
    ENJIN_EXPECT_FLOAT_EQ(m, 16.0f);
}

ENJIN_TEST_MAIN()
