#pragma once
// AUTO-GENERATED by _gen_compute.py -- do not edit by hand.
// Registry of embedded compute SPIR-V for shaders loaded through
// ComputePipelineHelper. In a dev tree the helper finds the loose .spv on
// disk; in a shipped Player there is no shader tree, so Create() falls back
// to this registry. Regenerate after editing any listed .comp source.

#include "Enjin/Platform/Platform.h"

namespace Enjin {
namespace Renderer {

struct EmbeddedComputeShader {
    const char* name;           // ComputePipelineHelper shader name, e.g. "particle_simulate.comp"
    const unsigned char* data;  // SPIR-V bytes
    unsigned size;
};

// Returns the registry entry for `name`, or nullptr if not embedded.
ENJIN_API const EmbeddedComputeShader* FindEmbeddedComputeShader(const char* name);

} // namespace Renderer
} // namespace Enjin
