#pragma once

#include "Enjin/Platform/Platform.h"
#include "Enjin/ECS/Components/Mesh.h"
#include <vector>
#include <array>

namespace Enjin {
namespace ECS {

// Level-of-Detail component with up to 5 LOD levels
// LOD 0 = full detail (original mesh), LOD 4 = lowest detail
struct LODComponent {
    static constexpr int MAX_LEVELS = 5;

    struct LODLevel {
        MeshComponent mesh;              // Simplified mesh for this level
        f32 maxDistance = 0.0f;           // Switch to next LOD beyond this distance
        u32 vertexCount = 0;             // Cached vertex count for display
        u32 triangleCount = 0;           // Cached triangle count for display
        f32 reductionRatio = 1.0f;       // What fraction of original (0.0-1.0)
    };

    // LOD levels (populated by auto-generation or manual assignment)
    std::array<LODLevel, MAX_LEVELS> levels;
    i32 levelCount = 0;                  // How many levels are populated (0 = no LOD)

    // Distance thresholds (defaults, overridable per-level)
    // These are camera-distance breakpoints
    f32 baseDistance = 10.0f;            // LOD 0 -> 1 transition distance
    f32 distanceMultiplier = 2.0f;       // Each level is N times farther

    // Runtime state
    i32 activeLOD = 0;                   // Currently displayed LOD level
    bool enabled = true;                 // LOD switching enabled
    bool autoGenerated = false;          // Was this LOD auto-generated?

    // Hysteresis: different thresholds for upgrading (higher detail) vs downgrading (lower detail).
    // Prevents rapid LOD flickering when camera is near a transition boundary.
    // Ratio of 0.1 means 10% dead-zone around each transition distance.
    f32 hysteresisRatio = 0.1f;

    // When true, LOD selection uses screen-space projected size (scale-aware)
    // instead of raw camera distance. More accurate for varying object scales.
    bool useScreenSize = true;

    // Reduction ratios for auto-generation (fraction of vertices to keep)
    // LOD 0 is always 1.0 (original), these are for LOD 1-4
    std::array<f32, MAX_LEVELS> reductionRatios = { 1.0f, 0.5f, 0.25f, 0.12f, 0.06f };
};

} // namespace ECS
} // namespace Enjin
