#pragma once

#include "Enjin/Platform/Platform.h"
#include "Enjin/ECS/Components/Mesh.h"
#include <vector>
#include <array>
#include <cmath>
#include <algorithm>

namespace Enjin {
namespace ECS {

// Level-of-Detail component with up to 5 LOD levels
// LOD 0 = full detail (original mesh), LOD 4 = lowest detail
struct LODComponent {
    static constexpr int MAX_LEVELS = 5;

    struct LODLevel {
        MeshComponent mesh;              // Simplified mesh for this level
        f32 maxDistance = 0.0f;           // Switch to next LOD beyond this distance
        u32 vertexCount = 0;             // Cached vertex count for display
        u32 triangleCount = 0;           // Cached triangle count for display
        f32 reductionRatio = 1.0f;       // What fraction of original (0.0-1.0)
    };

    // LOD levels (populated by auto-generation or manual assignment)
    std::array<LODLevel, MAX_LEVELS> levels;
    i32 levelCount = 0;                  // How many levels are populated (0 = no LOD)

    // Distance thresholds (defaults, overridable per-level)
    // These are camera-distance breakpoints
    f32 baseDistance = 10.0f;            // LOD 0 -> 1 transition distance
    f32 distanceMultiplier = 2.0f;       // Each level is N times farther

    // Stable size of the ORIGINAL (LOD 0) mesh — largest AABB extent, set once at
    // generation. The screen-size metric MUST use this, not the currently-active
    // (possibly already-swapped) mesh's bounds: otherwise swapping a LOD changes
    // the metric, the selection feeds back on itself, and it flickers every frame
    // — rebuilding GPU buffers until the retired-buffer graveyard runs out of
    // memory. 0 = unset (falls back to the live mesh bounds for old assets).
    f32 sourceMaxExtent = 0.0f;

    // Runtime state
    i32 activeLOD = 0;                   // Currently displayed LOD level
    bool enabled = true;                 // LOD switching enabled
    bool autoGenerated = false;          // Was this LOD auto-generated?

    // Hysteresis: different thresholds for upgrading (higher detail) vs downgrading (lower detail).
    // Prevents rapid LOD flickering when camera is near a transition boundary.
    // Ratio of 0.1 means 10% dead-zone around each transition distance.
    f32 hysteresisRatio = 0.1f;

    // When true, LOD selection uses screen-space projected size (scale-aware)
    // instead of raw camera distance. More accurate for varying object scales.
    bool useScreenSize = true;

    // Reduction ratios for auto-generation (fraction of vertices to keep)
    // LOD 0 is always 1.0 (original), these are for LOD 1-4
    std::array<f32, MAX_LEVELS> reductionRatios = { 1.0f, 0.5f, 0.25f, 0.12f, 0.06f };
};

// The stable object size the screen-size LOD metric divides by.
//
// It MUST be the ORIGINAL mesh's extent and never the currently-active LOD's: using the
// live mesh makes the metric depend on the level it just picked, so the selection
// oscillates every frame and rebuilds GPU buffers until it runs out of memory. That is a
// crash this engine has already had.
//
// `MeshSimplifier::GenerateLODs` records the extent. Anything older, or hand-built, has 0
// -- and the old fallback then read the LIVE mesh's cached AABB, which in a PLAYER is
// nobody's job to populate, so it sat at its unset sentinel (min 1,1,1 / max -1,-1,-1).
// `max - min` is NEGATIVE there, the caller's `Max(objectSize, 0.01f)` clamped it to 0.01,
// and the metric came out enormous: every legacy LOD in every exported game was pinned to
// its LOWEST mesh, permanently. Found 2026-09-21. The editor never showed it, because the
// inspector computes that AABB.
//
// So take the extent from whichever source can be trusted, in order, and BACK-FILL
// sourceMaxExtent -- a legacy LOD then gets the frame-to-frame stability a generated one
// has, and the walk over the vertices happens once instead of per frame.
//
// Returns 0 when there is nothing trustworthy to measure. The caller must then fall back
// to the entity's scale alone rather than guessing at a box, which is the rule
// IsEntityInFrustum already follows for the same cache.
inline f32 ResolveLODSourceExtent(LODComponent& lod, const MeshComponent* liveMesh) {
    if (lod.sourceMaxExtent > 0.0f) return lod.sourceMaxExtent;

    // LOD 0 is the original by construction; prefer it over the live mesh, which may
    // already have been swapped to a coarser level.
    const MeshComponent* src = nullptr;
    if (lod.levelCount > 0 && lod.levels[0].mesh.IsValid()) src = &lod.levels[0].mesh;
    else                                                    src = liveMesh;
    if (!src) return 0.0f;

    Math::Vector3 lo = src->cachedAABBMin, hi = src->cachedAABBMax;
    if (lo.x > hi.x) {
        // Unset. Compute from the vertices if they are still resident, but do NOT reload
        // them from the asset cache to answer a LOD query, and do not invent a box.
        if (src->vertices.empty()) return 0.0f;
        lo = Math::Vector3(1e30f, 1e30f, 1e30f);
        hi = Math::Vector3(-1e30f, -1e30f, -1e30f);
        for (const auto& v : src->vertices) {
            lo.x = std::min(lo.x, v.position.x); hi.x = std::max(hi.x, v.position.x);
            lo.y = std::min(lo.y, v.position.y); hi.y = std::max(hi.y, v.position.y);
            lo.z = std::min(lo.z, v.position.z); hi.z = std::max(hi.z, v.position.z);
        }
    }

    const Math::Vector3 ext = hi - lo;
    const f32 e = std::max(std::max(ext.x, ext.y), ext.z);
    if (!(e > 0.0f)) return 0.0f;   // also catches NaN
    lod.sourceMaxExtent = e;
    return e;
}

// Select which LOD index to display for `metric` (camera distance, or a
// distance/screen-size ratio when useScreenSize is on), given the current
// activeLOD. Directional hysteresis: upgrading to higher detail (lower index)
// requires the metric to be well inside a level's range (threshold - band);
// downgrading requires it to be well past (threshold + band). This prevents
// flicker at a transition boundary. A level's threshold falls back to
// baseDistance * distanceMultiplier^level when its maxDistance is unset (<= 0).
//
// This is the single source of truth for LOD selection — RenderSystem's LOD
// update calls it from both the distance-based and screen-size-based paths.
inline i32 SelectLOD(const LODComponent& lod, f32 metric) {
    if (lod.levelCount <= 1) return lod.activeLOD;
    i32 newLOD = lod.activeLOD;
    for (i32 l = 0; l < lod.levelCount - 1; ++l) {
        f32 threshold = lod.levels[l].maxDistance;
        if (threshold <= 0.0f) {
            threshold = lod.baseDistance * std::pow(lod.distanceMultiplier, static_cast<f32>(l));
        }
        f32 band = threshold * lod.hysteresisRatio;
        if (l < lod.activeLOD) {
            // Upgrade toward higher detail only when well inside this level's range.
            if (metric < threshold - band) { newLOD = l; break; }
        } else {
            // Downgrade toward lower detail when well past the band; otherwise stop.
            if (metric > threshold + band) newLOD = l + 1;
            else break;
        }
    }
    if (newLOD < 0) newLOD = 0;
    if (newLOD >= lod.levelCount) newLOD = lod.levelCount - 1;
    return newLOD;
}

} // namespace ECS
} // namespace Enjin
