#pragma once

#include "Enjin/Platform/Platform.h"
#include "Enjin/ECS/Components/Mesh.h"
#include <vector>
#include <array>
#include <cmath>

namespace Enjin {
namespace ECS {

// Level-of-Detail component with up to 5 LOD levels
// LOD 0 = full detail (original mesh), LOD 4 = lowest detail
struct LODComponent {
    static constexpr int MAX_LEVELS = 5;

    struct LODLevel {
        MeshComponent mesh;              // Simplified mesh for this level
        f32 maxDistance = 0.0f;           // Switch to next LOD beyond this distance
        u32 vertexCount = 0;             // Cached vertex count for display
        u32 triangleCount = 0;           // Cached triangle count for display
        f32 reductionRatio = 1.0f;       // What fraction of original (0.0-1.0)
    };

    // LOD levels (populated by auto-generation or manual assignment)
    std::array<LODLevel, MAX_LEVELS> levels;
    i32 levelCount = 0;                  // How many levels are populated (0 = no LOD)

    // Distance thresholds (defaults, overridable per-level)
    // These are camera-distance breakpoints
    f32 baseDistance = 10.0f;            // LOD 0 -> 1 transition distance
    f32 distanceMultiplier = 2.0f;       // Each level is N times farther

    // Runtime state
    i32 activeLOD = 0;                   // Currently displayed LOD level
    bool enabled = true;                 // LOD switching enabled
    bool autoGenerated = false;          // Was this LOD auto-generated?

    // Hysteresis: different thresholds for upgrading (higher detail) vs downgrading (lower detail).
    // Prevents rapid LOD flickering when camera is near a transition boundary.
    // Ratio of 0.1 means 10% dead-zone around each transition distance.
    f32 hysteresisRatio = 0.1f;

    // When true, LOD selection uses screen-space projected size (scale-aware)
    // instead of raw camera distance. More accurate for varying object scales.
    bool useScreenSize = true;

    // Reduction ratios for auto-generation (fraction of vertices to keep)
    // LOD 0 is always 1.0 (original), these are for LOD 1-4
    std::array<f32, MAX_LEVELS> reductionRatios = { 1.0f, 0.5f, 0.25f, 0.12f, 0.06f };
};

// Select which LOD index to display for `metric` (camera distance, or a
// distance/screen-size ratio when useScreenSize is on), given the current
// activeLOD. Directional hysteresis: upgrading to higher detail (lower index)
// requires the metric to be well inside a level's range (threshold - band);
// downgrading requires it to be well past (threshold + band). This prevents
// flicker at a transition boundary. A level's threshold falls back to
// baseDistance * distanceMultiplier^level when its maxDistance is unset (<= 0).
//
// This is the single source of truth for LOD selection — RenderSystem's LOD
// update calls it from both the distance-based and screen-size-based paths.
inline i32 SelectLOD(const LODComponent& lod, f32 metric) {
    if (lod.levelCount <= 1) return lod.activeLOD;
    i32 newLOD = lod.activeLOD;
    for (i32 l = 0; l < lod.levelCount - 1; ++l) {
        f32 threshold = lod.levels[l].maxDistance;
        if (threshold <= 0.0f) {
            threshold = lod.baseDistance * std::pow(lod.distanceMultiplier, static_cast<f32>(l));
        }
        f32 band = threshold * lod.hysteresisRatio;
        if (l < lod.activeLOD) {
            // Upgrade toward higher detail only when well inside this level's range.
            if (metric < threshold - band) { newLOD = l; break; }
        } else {
            // Downgrade toward lower detail when well past the band; otherwise stop.
            if (metric > threshold + band) newLOD = l + 1;
            else break;
        }
    }
    if (newLOD < 0) newLOD = 0;
    if (newLOD >= lod.levelCount) newLOD = lod.levelCount - 1;
    return newLOD;
}

} // namespace ECS
} // namespace Enjin
